license:
  main: bsd-x11
  report_missing: false
  additional:
    - bsd-new
    - apache-2.0
  category: Permissive
copyright:
  check: false
exclude:
  extensions:
    - yml
    - yaml
    - html
    - rst
    - conf
    - cfg
  langs:
    - HTML

