/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/* pa0_gpio */
#define PA0_GPIO \
	SAM_PINMUX(a, 0, gpio, gpio)

/* pa0a_tc0_tiob0 */
#define PA0A_TC0_TIOB0 \
	SAM_PINMUX(a, 0, a, periph)

/* pa0b_spi_npcs1 */
#define PA0B_SPI_NPCS1 \
	SAM_PINMUX(a, 0, b, periph)

/* pa0x_supc_wkup0 */
#define PA0X_SUPC_WKUP0 \
	SAM_PINMUX(a, 0, x, extra)

/* pa1_gpio */
#define PA1_GPIO \
	SAM_PINMUX(a, 1, gpio, gpio)

/* pa1a_tc0_tioa0 */
#define PA1A_TC0_TIOA0 \
	SAM_PINMUX(a, 1, a, periph)

/* pa1b_spi_npcs2 */
#define PA1B_SPI_NPCS2 \
	SAM_PINMUX(a, 1, b, periph)

/* pa1x_supc_wkup1 */
#define PA1X_SUPC_WKUP1 \
	SAM_PINMUX(a, 1, x, extra)

/* pa2_gpio */
#define PA2_GPIO \
	SAM_PINMUX(a, 2, gpio, gpio)

/* pa2a_tc0_tclk0 */
#define PA2A_TC0_TCLK0 \
	SAM_PINMUX(a, 2, a, periph)

/* pa2b_adc_adtrg */
#define PA2B_ADC_ADTRG \
	SAM_PINMUX(a, 2, b, periph)

/* pa2x_supc_wkup2 */
#define PA2X_SUPC_WKUP2 \
	SAM_PINMUX(a, 2, x, extra)

/* pa3_gpio */
#define PA3_GPIO \
	SAM_PINMUX(a, 3, gpio, gpio)

/* pa3a_hsmci_mcck */
#define PA3A_HSMCI_MCCK \
	SAM_PINMUX(a, 3, a, periph)

/* pa3b_pmc_pck1 */
#define PA3B_PMC_PCK1 \
	SAM_PINMUX(a, 3, b, periph)

/* pa4_gpio */
#define PA4_GPIO \
	SAM_PINMUX(a, 4, gpio, gpio)

/* pa4a_hsmci_mccda */
#define PA4A_HSMCI_MCCDA \
	SAM_PINMUX(a, 4, a, periph)

/* pa4b_pwm_pwmh0 */
#define PA4B_PWM_PWMH0 \
	SAM_PINMUX(a, 4, b, periph)

/* pa5_gpio */
#define PA5_GPIO \
	SAM_PINMUX(a, 5, gpio, gpio)

/* pa5a_hsmci_mcda0 */
#define PA5A_HSMCI_MCDA0 \
	SAM_PINMUX(a, 5, a, periph)

/* pa5b_pwm_pwmh1 */
#define PA5B_PWM_PWMH1 \
	SAM_PINMUX(a, 5, b, periph)

/* pa6_gpio */
#define PA6_GPIO \
	SAM_PINMUX(a, 6, gpio, gpio)

/* pa6a_hsmci_mcda1 */
#define PA6A_HSMCI_MCDA1 \
	SAM_PINMUX(a, 6, a, periph)

/* pa6b_pwm_pwmh2 */
#define PA6B_PWM_PWMH2 \
	SAM_PINMUX(a, 6, b, periph)

/* pa7_gpio */
#define PA7_GPIO \
	SAM_PINMUX(a, 7, gpio, gpio)

/* pa7a_hsmci_mcda2 */
#define PA7A_HSMCI_MCDA2 \
	SAM_PINMUX(a, 7, a, periph)

/* pa7b_pwm_pwml0 */
#define PA7B_PWM_PWML0 \
	SAM_PINMUX(a, 7, b, periph)

/* pa8_gpio */
#define PA8_GPIO \
	SAM_PINMUX(a, 8, gpio, gpio)

/* pa8a_hsmci_mcda3 */
#define PA8A_HSMCI_MCDA3 \
	SAM_PINMUX(a, 8, a, periph)

/* pa8b_pwm_pwml1 */
#define PA8B_PWM_PWML1 \
	SAM_PINMUX(a, 8, b, periph)

/* pa9_gpio */
#define PA9_GPIO \
	SAM_PINMUX(a, 9, gpio, gpio)

/* pa9a_twi0_twd0 */
#define PA9A_TWI0_TWD0 \
	SAM_PINMUX(a, 9, a, periph)

/* pa9b_pwm_pwml2 */
#define PA9B_PWM_PWML2 \
	SAM_PINMUX(a, 9, b, periph)

/* pa9x_supc_wkup3 */
#define PA9X_SUPC_WKUP3 \
	SAM_PINMUX(a, 9, x, extra)

/* pa10_gpio */
#define PA10_GPIO \
	SAM_PINMUX(a, 10, gpio, gpio)

/* pa10a_twi0_twck0 */
#define PA10A_TWI0_TWCK0 \
	SAM_PINMUX(a, 10, a, periph)

/* pa10b_pwm_pwml3 */
#define PA10B_PWM_PWML3 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10x_supc_wkup4 */
#define PA10X_SUPC_WKUP4 \
	SAM_PINMUX(a, 10, x, extra)

/* pa11_gpio */
#define PA11_GPIO \
	SAM_PINMUX(a, 11, gpio, gpio)

/* pa11a_uart_urxd */
#define PA11A_UART_URXD \
	SAM_PINMUX(a, 11, a, periph)

/* pa11b_pwm_pwmfi0 */
#define PA11B_PWM_PWMFI0 \
	SAM_PINMUX(a, 11, b, periph)

/* pa12_gpio */
#define PA12_GPIO \
	SAM_PINMUX(a, 12, gpio, gpio)

/* pa12a_uart_utxd */
#define PA12A_UART_UTXD \
	SAM_PINMUX(a, 12, a, periph)

/* pa12b_pwm_pwmfi1 */
#define PA12B_PWM_PWMFI1 \
	SAM_PINMUX(a, 12, b, periph)

/* pa13_gpio */
#define PA13_GPIO \
	SAM_PINMUX(a, 13, gpio, gpio)

/* pa13a_spi_miso */
#define PA13A_SPI_MISO \
	SAM_PINMUX(a, 13, a, periph)

/* pa14_gpio */
#define PA14_GPIO \
	SAM_PINMUX(a, 14, gpio, gpio)

/* pa14a_spi_mosi */
#define PA14A_SPI_MOSI \
	SAM_PINMUX(a, 14, a, periph)

/* pa15_gpio */
#define PA15_GPIO \
	SAM_PINMUX(a, 15, gpio, gpio)

/* pa15a_spi_spck */
#define PA15A_SPI_SPCK \
	SAM_PINMUX(a, 15, a, periph)

/* pa15b_pwm_pwmh2 */
#define PA15B_PWM_PWMH2 \
	SAM_PINMUX(a, 15, b, periph)

/* pa16_gpio */
#define PA16_GPIO \
	SAM_PINMUX(a, 16, gpio, gpio)

/* pa16a_spi_npcs0 */
#define PA16A_SPI_NPCS0 \
	SAM_PINMUX(a, 16, a, periph)

/* pa16b_ebi_ncs1 */
#define PA16B_EBI_NCS1 \
	SAM_PINMUX(a, 16, b, periph)

/* pa16x_supc_wkup5 */
#define PA16X_SUPC_WKUP5 \
	SAM_PINMUX(a, 16, x, extra)

/* pa17_gpio */
#define PA17_GPIO \
	SAM_PINMUX(a, 17, gpio, gpio)

/* pa17a_usart0_sck0 */
#define PA17A_USART0_SCK0 \
	SAM_PINMUX(a, 17, a, periph)

/* pa17b_adc_ad12btrg */
#define PA17B_ADC_AD12BTRG \
	SAM_PINMUX(a, 17, b, periph)

/* pa17x_supc_wkup6 */
#define PA17X_SUPC_WKUP6 \
	SAM_PINMUX(a, 17, x, extra)

/* pa18_gpio */
#define PA18_GPIO \
	SAM_PINMUX(a, 18, gpio, gpio)

/* pa18a_usart0_txd0 */
#define PA18A_USART0_TXD0 \
	SAM_PINMUX(a, 18, a, periph)

/* pa18b_pwm_pwmfi2 */
#define PA18B_PWM_PWMFI2 \
	SAM_PINMUX(a, 18, b, periph)

/* pa18x_supc_wkup7 */
#define PA18X_SUPC_WKUP7 \
	SAM_PINMUX(a, 18, x, extra)

/* pa19_gpio */
#define PA19_GPIO \
	SAM_PINMUX(a, 19, gpio, gpio)

/* pa19a_usart0_rxd0 */
#define PA19A_USART0_RXD0 \
	SAM_PINMUX(a, 19, a, periph)

/* pa19b_spi_npcs3 */
#define PA19B_SPI_NPCS3 \
	SAM_PINMUX(a, 19, b, periph)

/* pa19x_supc_wkup8 */
#define PA19X_SUPC_WKUP8 \
	SAM_PINMUX(a, 19, x, extra)

/* pa20_gpio */
#define PA20_GPIO \
	SAM_PINMUX(a, 20, gpio, gpio)

/* pa20a_usart1_txd1 */
#define PA20A_USART1_TXD1 \
	SAM_PINMUX(a, 20, a, periph)

/* pa20b_pwm_pwmh3 */
#define PA20B_PWM_PWMH3 \
	SAM_PINMUX(a, 20, b, periph)

/* pa20x_supc_wkup9 */
#define PA20X_SUPC_WKUP9 \
	SAM_PINMUX(a, 20, x, extra)

/* pa21_gpio */
#define PA21_GPIO \
	SAM_PINMUX(a, 21, gpio, gpio)

/* pa21a_usart1_rxd1 */
#define PA21A_USART1_RXD1 \
	SAM_PINMUX(a, 21, a, periph)

/* pa21b_pmc_pck0 */
#define PA21B_PMC_PCK0 \
	SAM_PINMUX(a, 21, b, periph)

/* pa21x_supc_wkup10 */
#define PA21X_SUPC_WKUP10 \
	SAM_PINMUX(a, 21, x, extra)

/* pa22_gpio */
#define PA22_GPIO \
	SAM_PINMUX(a, 22, gpio, gpio)

/* pa22a_usart2_txd2 */
#define PA22A_USART2_TXD2 \
	SAM_PINMUX(a, 22, a, periph)

/* pa22b_usart1_rts1 */
#define PA22B_USART1_RTS1 \
	SAM_PINMUX(a, 22, b, periph)

/* pa22x_adc_ad12b0 */
#define PA22X_ADC_AD12B0 \
	SAM_PINMUX(a, 22, x, extra)

/* pa23_gpio */
#define PA23_GPIO \
	SAM_PINMUX(a, 23, gpio, gpio)

/* pa23a_usart2_rxd2 */
#define PA23A_USART2_RXD2 \
	SAM_PINMUX(a, 23, a, periph)

/* pa23b_usart1_cts1 */
#define PA23B_USART1_CTS1 \
	SAM_PINMUX(a, 23, b, periph)

/* pa24_gpio */
#define PA24_GPIO \
	SAM_PINMUX(a, 24, gpio, gpio)

/* pa24a_twi1_twd1 */
#define PA24A_TWI1_TWD1 \
	SAM_PINMUX(a, 24, a, periph)

/* pa24b_usart1_sck1 */
#define PA24B_USART1_SCK1 \
	SAM_PINMUX(a, 24, b, periph)

/* pa24x_supc_wkup11 */
#define PA24X_SUPC_WKUP11 \
	SAM_PINMUX(a, 24, x, extra)

/* pa25_gpio */
#define PA25_GPIO \
	SAM_PINMUX(a, 25, gpio, gpio)

/* pa25a_twi1_twck1 */
#define PA25A_TWI1_TWCK1 \
	SAM_PINMUX(a, 25, a, periph)

/* pa25b_usart2_sck2 */
#define PA25B_USART2_SCK2 \
	SAM_PINMUX(a, 25, b, periph)

/* pa25x_supc_wkup12 */
#define PA25X_SUPC_WKUP12 \
	SAM_PINMUX(a, 25, x, extra)

/* pa26_gpio */
#define PA26_GPIO \
	SAM_PINMUX(a, 26, gpio, gpio)

/* pa26a_ssc_td */
#define PA26A_SSC_TD \
	SAM_PINMUX(a, 26, a, periph)

/* pa26b_tc0_tclk2 */
#define PA26B_TC0_TCLK2 \
	SAM_PINMUX(a, 26, b, periph)

/* pa27_gpio */
#define PA27_GPIO \
	SAM_PINMUX(a, 27, gpio, gpio)

/* pa27a_ssc_rd */
#define PA27A_SSC_RD \
	SAM_PINMUX(a, 27, a, periph)

/* pa27b_pmc_pck0 */
#define PA27B_PMC_PCK0 \
	SAM_PINMUX(a, 27, b, periph)

/* pa28_gpio */
#define PA28_GPIO \
	SAM_PINMUX(a, 28, gpio, gpio)

/* pa28a_ssc_tk */
#define PA28A_SSC_TK \
	SAM_PINMUX(a, 28, a, periph)

/* pa28b_pwm_pwmh0 */
#define PA28B_PWM_PWMH0 \
	SAM_PINMUX(a, 28, b, periph)

/* pa29_gpio */
#define PA29_GPIO \
	SAM_PINMUX(a, 29, gpio, gpio)

/* pa29a_ssc_rk */
#define PA29A_SSC_RK \
	SAM_PINMUX(a, 29, a, periph)

/* pa29b_pwm_pwmh1 */
#define PA29B_PWM_PWMH1 \
	SAM_PINMUX(a, 29, b, periph)

/* pa30_gpio */
#define PA30_GPIO \
	SAM_PINMUX(a, 30, gpio, gpio)

/* pa30a_ssc_tf */
#define PA30A_SSC_TF \
	SAM_PINMUX(a, 30, a, periph)

/* pa30b_tc0_tioa2 */
#define PA30B_TC0_TIOA2 \
	SAM_PINMUX(a, 30, b, periph)

/* pa30x_adc_ad12b1 */
#define PA30X_ADC_AD12B1 \
	SAM_PINMUX(a, 30, x, extra)

/* pa31_gpio */
#define PA31_GPIO \
	SAM_PINMUX(a, 31, gpio, gpio)

/* pa31a_ssc_rf */
#define PA31A_SSC_RF \
	SAM_PINMUX(a, 31, a, periph)

/* pa31b_tc0_tiob2 */
#define PA31B_TC0_TIOB2 \
	SAM_PINMUX(a, 31, b, periph)

/* pb0_gpio */
#define PB0_GPIO \
	SAM_PINMUX(b, 0, gpio, gpio)

/* pb0a_pwm_pwmh0 */
#define PB0A_PWM_PWMH0 \
	SAM_PINMUX(b, 0, a, periph)

/* pb0b_ebi_a2 */
#define PB0B_EBI_A2 \
	SAM_PINMUX(b, 0, b, periph)

/* pb0x_supc_wkup13 */
#define PB0X_SUPC_WKUP13 \
	SAM_PINMUX(b, 0, x, extra)

/* pb1_gpio */
#define PB1_GPIO \
	SAM_PINMUX(b, 1, gpio, gpio)

/* pb1a_pwm_pwmh1 */
#define PB1A_PWM_PWMH1 \
	SAM_PINMUX(b, 1, a, periph)

/* pb1b_ebi_a3 */
#define PB1B_EBI_A3 \
	SAM_PINMUX(b, 1, b, periph)

/* pb1x_supc_wkup14 */
#define PB1X_SUPC_WKUP14 \
	SAM_PINMUX(b, 1, x, extra)

/* pb2_gpio */
#define PB2_GPIO \
	SAM_PINMUX(b, 2, gpio, gpio)

/* pb2a_pwm_pwmh2 */
#define PB2A_PWM_PWMH2 \
	SAM_PINMUX(b, 2, a, periph)

/* pb2b_ebi_a4 */
#define PB2B_EBI_A4 \
	SAM_PINMUX(b, 2, b, periph)

/* pb2x_supc_wkup15 */
#define PB2X_SUPC_WKUP15 \
	SAM_PINMUX(b, 2, x, extra)

/* pb3_gpio */
#define PB3_GPIO \
	SAM_PINMUX(b, 3, gpio, gpio)

/* pb3a_pwm_pwmh3 */
#define PB3A_PWM_PWMH3 \
	SAM_PINMUX(b, 3, a, periph)

/* pb3b_ebi_a5 */
#define PB3B_EBI_A5 \
	SAM_PINMUX(b, 3, b, periph)

/* pb3x_adc_ad12b2 */
#define PB3X_ADC_AD12B2 \
	SAM_PINMUX(b, 3, x, extra)

/* pb4_gpio */
#define PB4_GPIO \
	SAM_PINMUX(b, 4, gpio, gpio)

/* pb4a_tc0_tclk1 */
#define PB4A_TC0_TCLK1 \
	SAM_PINMUX(b, 4, a, periph)

/* pb4b_ebi_a6 */
#define PB4B_EBI_A6 \
	SAM_PINMUX(b, 4, b, periph)

/* pb4x_adc_ad12b3 */
#define PB4X_ADC_AD12B3 \
	SAM_PINMUX(b, 4, x, extra)

/* pb5_gpio */
#define PB5_GPIO \
	SAM_PINMUX(b, 5, gpio, gpio)

/* pb5a_tc0_tioa1 */
#define PB5A_TC0_TIOA1 \
	SAM_PINMUX(b, 5, a, periph)

/* pb5b_ebi_a7 */
#define PB5B_EBI_A7 \
	SAM_PINMUX(b, 5, b, periph)

/* pb5x_adc_ad0 */
#define PB5X_ADC_AD0 \
	SAM_PINMUX(b, 5, x, extra)

/* pb6_gpio */
#define PB6_GPIO \
	SAM_PINMUX(b, 6, gpio, gpio)

/* pb6a_tc0_tiob1 */
#define PB6A_TC0_TIOB1 \
	SAM_PINMUX(b, 6, a, periph)

/* pb6b_ebi_d15 */
#define PB6B_EBI_D15 \
	SAM_PINMUX(b, 6, b, periph)

/* pb6x_adc_ad1 */
#define PB6X_ADC_AD1 \
	SAM_PINMUX(b, 6, x, extra)

/* pb7_gpio */
#define PB7_GPIO \
	SAM_PINMUX(b, 7, gpio, gpio)

/* pb7a_usart0_rts0 */
#define PB7A_USART0_RTS0 \
	SAM_PINMUX(b, 7, a, periph)

/* pb7b_ebi_a0_nbs0 */
#define PB7B_EBI_A0_NBS0 \
	SAM_PINMUX(b, 7, b, periph)

/* pb7x_adc_ad2 */
#define PB7X_ADC_AD2 \
	SAM_PINMUX(b, 7, x, extra)

/* pb8_gpio */
#define PB8_GPIO \
	SAM_PINMUX(b, 8, gpio, gpio)

/* pb8a_usart0_cts0 */
#define PB8A_USART0_CTS0 \
	SAM_PINMUX(b, 8, a, periph)

/* pb8b_ebi_a1 */
#define PB8B_EBI_A1 \
	SAM_PINMUX(b, 8, b, periph)

/* pb8x_adc_ad3 */
#define PB8X_ADC_AD3 \
	SAM_PINMUX(b, 8, x, extra)

/* pb9_gpio */
#define PB9_GPIO \
	SAM_PINMUX(b, 9, gpio, gpio)

/* pb9a_ebi_d0 */
#define PB9A_EBI_D0 \
	SAM_PINMUX(b, 9, a, periph)

/* pb9b_usart0_dtr0 */
#define PB9B_USART0_DTR0 \
	SAM_PINMUX(b, 9, b, periph)

/* pb10_gpio */
#define PB10_GPIO \
	SAM_PINMUX(b, 10, gpio, gpio)

/* pb10a_ebi_d1 */
#define PB10A_EBI_D1 \
	SAM_PINMUX(b, 10, a, periph)

/* pb10b_usart0_dsr0 */
#define PB10B_USART0_DSR0 \
	SAM_PINMUX(b, 10, b, periph)

/* pb11_gpio */
#define PB11_GPIO \
	SAM_PINMUX(b, 11, gpio, gpio)

/* pb11a_ebi_d2 */
#define PB11A_EBI_D2 \
	SAM_PINMUX(b, 11, a, periph)

/* pb11b_usart0_dcd0 */
#define PB11B_USART0_DCD0 \
	SAM_PINMUX(b, 11, b, periph)

/* pb12_gpio */
#define PB12_GPIO \
	SAM_PINMUX(b, 12, gpio, gpio)

/* pb12a_ebi_d3 */
#define PB12A_EBI_D3 \
	SAM_PINMUX(b, 12, a, periph)

/* pb12b_usart0_ri0 */
#define PB12B_USART0_RI0 \
	SAM_PINMUX(b, 12, b, periph)

/* pb13_gpio */
#define PB13_GPIO \
	SAM_PINMUX(b, 13, gpio, gpio)

/* pb13a_ebi_d4 */
#define PB13A_EBI_D4 \
	SAM_PINMUX(b, 13, a, periph)

/* pb13b_pwm_pwmh0 */
#define PB13B_PWM_PWMH0 \
	SAM_PINMUX(b, 13, b, periph)

/* pb14_gpio */
#define PB14_GPIO \
	SAM_PINMUX(b, 14, gpio, gpio)

/* pb14a_ebi_d5 */
#define PB14A_EBI_D5 \
	SAM_PINMUX(b, 14, a, periph)

/* pb14b_pwm_pwmh1 */
#define PB14B_PWM_PWMH1 \
	SAM_PINMUX(b, 14, b, periph)

/* pb15_gpio */
#define PB15_GPIO \
	SAM_PINMUX(b, 15, gpio, gpio)

/* pb15a_ebi_d6 */
#define PB15A_EBI_D6 \
	SAM_PINMUX(b, 15, a, periph)

/* pb15b_pwm_pwmh2 */
#define PB15B_PWM_PWMH2 \
	SAM_PINMUX(b, 15, b, periph)

/* pb16_gpio */
#define PB16_GPIO \
	SAM_PINMUX(b, 16, gpio, gpio)

/* pb16a_ebi_d7 */
#define PB16A_EBI_D7 \
	SAM_PINMUX(b, 16, a, periph)

/* pb16b_pwm_pwmh3 */
#define PB16B_PWM_PWMH3 \
	SAM_PINMUX(b, 16, b, periph)

/* pb17_gpio */
#define PB17_GPIO \
	SAM_PINMUX(b, 17, gpio, gpio)

/* pb17a_ebi_nandoe */
#define PB17A_EBI_NANDOE \
	SAM_PINMUX(b, 17, a, periph)

/* pb17b_pwm_pwml0 */
#define PB17B_PWM_PWML0 \
	SAM_PINMUX(b, 17, b, periph)

/* pb18_gpio */
#define PB18_GPIO \
	SAM_PINMUX(b, 18, gpio, gpio)

/* pb18a_ebi_nandwe */
#define PB18A_EBI_NANDWE \
	SAM_PINMUX(b, 18, a, periph)

/* pb18b_pwm_pwml1 */
#define PB18B_PWM_PWML1 \
	SAM_PINMUX(b, 18, b, periph)

/* pb19_gpio */
#define PB19_GPIO \
	SAM_PINMUX(b, 19, gpio, gpio)

/* pb19a_ebi_nrd */
#define PB19A_EBI_NRD \
	SAM_PINMUX(b, 19, a, periph)

/* pb19b_pwm_pwml2 */
#define PB19B_PWM_PWML2 \
	SAM_PINMUX(b, 19, b, periph)

/* pb20_gpio */
#define PB20_GPIO \
	SAM_PINMUX(b, 20, gpio, gpio)

/* pb20a_ebi_ncs0 */
#define PB20A_EBI_NCS0 \
	SAM_PINMUX(b, 20, a, periph)

/* pb20b_pwm_pwml3 */
#define PB20B_PWM_PWML3 \
	SAM_PINMUX(b, 20, b, periph)

/* pb21_gpio */
#define PB21_GPIO \
	SAM_PINMUX(b, 21, gpio, gpio)

/* pb21a_ebi_a21_nandale */
#define PB21A_EBI_A21_NANDALE \
	SAM_PINMUX(b, 21, a, periph)

/* pb21b_usart2_rts2 */
#define PB21B_USART2_RTS2 \
	SAM_PINMUX(b, 21, b, periph)

/* pb22_gpio */
#define PB22_GPIO \
	SAM_PINMUX(b, 22, gpio, gpio)

/* pb22a_ebi_a22_nandcle */
#define PB22A_EBI_A22_NANDCLE \
	SAM_PINMUX(b, 22, a, periph)

/* pb22b_usart2_cts2 */
#define PB22B_USART2_CTS2 \
	SAM_PINMUX(b, 22, b, periph)

/* pb23_gpio */
#define PB23_GPIO \
	SAM_PINMUX(b, 23, gpio, gpio)

/* pb23a_ebi_nwr0_nwe */
#define PB23A_EBI_NWR0_NWE \
	SAM_PINMUX(b, 23, a, periph)

/* pb23b_pmc_pck2 */
#define PB23B_PMC_PCK2 \
	SAM_PINMUX(b, 23, b, periph)

/* pb24_gpio */
#define PB24_GPIO \
	SAM_PINMUX(b, 24, gpio, gpio)

/* pb24a_ebi_nandrdy */
#define PB24A_EBI_NANDRDY \
	SAM_PINMUX(b, 24, a, periph)

/* pb24b_pmc_pck1 */
#define PB24B_PMC_PCK1 \
	SAM_PINMUX(b, 24, b, periph)

/* pb25_gpio */
#define PB25_GPIO \
	SAM_PINMUX(b, 25, gpio, gpio)

/* pb25a_ebi_d8 */
#define PB25A_EBI_D8 \
	SAM_PINMUX(b, 25, a, periph)

/* pb25b_pwm_pwml0 */
#define PB25B_PWM_PWML0 \
	SAM_PINMUX(b, 25, b, periph)

/* pb26_gpio */
#define PB26_GPIO \
	SAM_PINMUX(b, 26, gpio, gpio)

/* pb26a_ebi_d9 */
#define PB26A_EBI_D9 \
	SAM_PINMUX(b, 26, a, periph)

/* pb26b_pwm_pwml1 */
#define PB26B_PWM_PWML1 \
	SAM_PINMUX(b, 26, b, periph)

/* pb27_gpio */
#define PB27_GPIO \
	SAM_PINMUX(b, 27, gpio, gpio)

/* pb27a_ebi_d10 */
#define PB27A_EBI_D10 \
	SAM_PINMUX(b, 27, a, periph)

/* pb27b_pwm_pwml2 */
#define PB27B_PWM_PWML2 \
	SAM_PINMUX(b, 27, b, periph)

/* pb28_gpio */
#define PB28_GPIO \
	SAM_PINMUX(b, 28, gpio, gpio)

/* pb28a_ebi_d11 */
#define PB28A_EBI_D11 \
	SAM_PINMUX(b, 28, a, periph)

/* pb28b_pwm_pwml3 */
#define PB28B_PWM_PWML3 \
	SAM_PINMUX(b, 28, b, periph)

/* pb29_gpio */
#define PB29_GPIO \
	SAM_PINMUX(b, 29, gpio, gpio)

/* pb29a_ebi_d12 */
#define PB29A_EBI_D12 \
	SAM_PINMUX(b, 29, a, periph)

/* pb30_gpio */
#define PB30_GPIO \
	SAM_PINMUX(b, 30, gpio, gpio)

/* pb30a_ebi_d13 */
#define PB30A_EBI_D13 \
	SAM_PINMUX(b, 30, a, periph)

/* pb31_gpio */
#define PB31_GPIO \
	SAM_PINMUX(b, 31, gpio, gpio)

/* pb31a_ebi_d14 */
#define PB31A_EBI_D14 \
	SAM_PINMUX(b, 31, a, periph)

/* pc0_gpio */
#define PC0_GPIO \
	SAM_PINMUX(c, 0, gpio, gpio)

/* pc0a_ebi_a2 */
#define PC0A_EBI_A2 \
	SAM_PINMUX(c, 0, a, periph)

/* pc1_gpio */
#define PC1_GPIO \
	SAM_PINMUX(c, 1, gpio, gpio)

/* pc1a_ebi_a3 */
#define PC1A_EBI_A3 \
	SAM_PINMUX(c, 1, a, periph)

/* pc2_gpio */
#define PC2_GPIO \
	SAM_PINMUX(c, 2, gpio, gpio)

/* pc2a_ebi_a4 */
#define PC2A_EBI_A4 \
	SAM_PINMUX(c, 2, a, periph)

/* pc3_gpio */
#define PC3_GPIO \
	SAM_PINMUX(c, 3, gpio, gpio)

/* pc3a_ebi_a5 */
#define PC3A_EBI_A5 \
	SAM_PINMUX(c, 3, a, periph)

/* pc3b_spi_npcs1 */
#define PC3B_SPI_NPCS1 \
	SAM_PINMUX(c, 3, b, periph)

/* pc4_gpio */
#define PC4_GPIO \
	SAM_PINMUX(c, 4, gpio, gpio)

/* pc4a_ebi_a6 */
#define PC4A_EBI_A6 \
	SAM_PINMUX(c, 4, a, periph)

/* pc4b_spi_npcs2 */
#define PC4B_SPI_NPCS2 \
	SAM_PINMUX(c, 4, b, periph)

/* pc5_gpio */
#define PC5_GPIO \
	SAM_PINMUX(c, 5, gpio, gpio)

/* pc5a_ebi_a7 */
#define PC5A_EBI_A7 \
	SAM_PINMUX(c, 5, a, periph)

/* pc5b_spi_npcs3 */
#define PC5B_SPI_NPCS3 \
	SAM_PINMUX(c, 5, b, periph)

/* pc6_gpio */
#define PC6_GPIO \
	SAM_PINMUX(c, 6, gpio, gpio)

/* pc6a_ebi_a8 */
#define PC6A_EBI_A8 \
	SAM_PINMUX(c, 6, a, periph)

/* pc6b_pwm_pwml0 */
#define PC6B_PWM_PWML0 \
	SAM_PINMUX(c, 6, b, periph)

/* pc7_gpio */
#define PC7_GPIO \
	SAM_PINMUX(c, 7, gpio, gpio)

/* pc7a_ebi_a9 */
#define PC7A_EBI_A9 \
	SAM_PINMUX(c, 7, a, periph)

/* pc7b_pwm_pwml1 */
#define PC7B_PWM_PWML1 \
	SAM_PINMUX(c, 7, b, periph)

/* pc8_gpio */
#define PC8_GPIO \
	SAM_PINMUX(c, 8, gpio, gpio)

/* pc8a_ebi_a10 */
#define PC8A_EBI_A10 \
	SAM_PINMUX(c, 8, a, periph)

/* pc8b_pwm_pwml2 */
#define PC8B_PWM_PWML2 \
	SAM_PINMUX(c, 8, b, periph)

/* pc9_gpio */
#define PC9_GPIO \
	SAM_PINMUX(c, 9, gpio, gpio)

/* pc9a_ebi_a11 */
#define PC9A_EBI_A11 \
	SAM_PINMUX(c, 9, a, periph)

/* pc9b_pwm_pwml3 */
#define PC9B_PWM_PWML3 \
	SAM_PINMUX(c, 9, b, periph)

/* pc10_gpio */
#define PC10_GPIO \
	SAM_PINMUX(c, 10, gpio, gpio)

/* pc10a_ebi_a12 */
#define PC10A_EBI_A12 \
	SAM_PINMUX(c, 10, a, periph)

/* pc10b_usart3_cts3 */
#define PC10B_USART3_CTS3 \
	SAM_PINMUX(c, 10, b, periph)

/* pc11_gpio */
#define PC11_GPIO \
	SAM_PINMUX(c, 11, gpio, gpio)

/* pc11a_ebi_a13 */
#define PC11A_EBI_A13 \
	SAM_PINMUX(c, 11, a, periph)

/* pc11b_usart3_rts3 */
#define PC11B_USART3_RTS3 \
	SAM_PINMUX(c, 11, b, periph)

/* pc12_gpio */
#define PC12_GPIO \
	SAM_PINMUX(c, 12, gpio, gpio)

/* pc12a_ebi_ncs1 */
#define PC12A_EBI_NCS1 \
	SAM_PINMUX(c, 12, a, periph)

/* pc12b_usart3_txd3 */
#define PC12B_USART3_TXD3 \
	SAM_PINMUX(c, 12, b, periph)

/* pc13_gpio */
#define PC13_GPIO \
	SAM_PINMUX(c, 13, gpio, gpio)

/* pc13a_ebi_a2 */
#define PC13A_EBI_A2 \
	SAM_PINMUX(c, 13, a, periph)

/* pc13b_usart3_rxd3 */
#define PC13B_USART3_RXD3 \
	SAM_PINMUX(c, 13, b, periph)

/* pc14_gpio */
#define PC14_GPIO \
	SAM_PINMUX(c, 14, gpio, gpio)

/* pc14a_ebi_a3 */
#define PC14A_EBI_A3 \
	SAM_PINMUX(c, 14, a, periph)

/* pc14b_spi_npcs2 */
#define PC14B_SPI_NPCS2 \
	SAM_PINMUX(c, 14, b, periph)

/* pc15_gpio */
#define PC15_GPIO \
	SAM_PINMUX(c, 15, gpio, gpio)

/* pc15a_ebi_nwr1_nbs1 */
#define PC15A_EBI_NWR1_NBS1 \
	SAM_PINMUX(c, 15, a, periph)

/* pc15x_adc_ad12b4 */
#define PC15X_ADC_AD12B4 \
	SAM_PINMUX(c, 15, x, extra)

/* pc16_gpio */
#define PC16_GPIO \
	SAM_PINMUX(c, 16, gpio, gpio)

/* pc16a_ebi_ncs2 */
#define PC16A_EBI_NCS2 \
	SAM_PINMUX(c, 16, a, periph)

/* pc16b_pwm_pwml3 */
#define PC16B_PWM_PWML3 \
	SAM_PINMUX(c, 16, b, periph)

/* pc16x_adc_ad12b5 */
#define PC16X_ADC_AD12B5 \
	SAM_PINMUX(c, 16, x, extra)

/* pc17_gpio */
#define PC17_GPIO \
	SAM_PINMUX(c, 17, gpio, gpio)

/* pc17a_ebi_ncs3 */
#define PC17A_EBI_NCS3 \
	SAM_PINMUX(c, 17, a, periph)

/* pc17x_adc_ad12b6 */
#define PC17X_ADC_AD12B6 \
	SAM_PINMUX(c, 17, x, extra)

/* pc18_gpio */
#define PC18_GPIO \
	SAM_PINMUX(c, 18, gpio, gpio)

/* pc18a_ebi_nwait */
#define PC18A_EBI_NWAIT \
	SAM_PINMUX(c, 18, a, periph)

/* pc18x_adc_ad12b7 */
#define PC18X_ADC_AD12B7 \
	SAM_PINMUX(c, 18, x, extra)

/* pc19_gpio */
#define PC19_GPIO \
	SAM_PINMUX(c, 19, gpio, gpio)

/* pc19a_usart3_sck3 */
#define PC19A_USART3_SCK3 \
	SAM_PINMUX(c, 19, a, periph)

/* pc19b_spi_npcs1 */
#define PC19B_SPI_NPCS1 \
	SAM_PINMUX(c, 19, b, periph)

/* pc20_gpio */
#define PC20_GPIO \
	SAM_PINMUX(c, 20, gpio, gpio)

/* pc20a_ebi_a14 */
#define PC20A_EBI_A14 \
	SAM_PINMUX(c, 20, a, periph)

/* pc21_gpio */
#define PC21_GPIO \
	SAM_PINMUX(c, 21, gpio, gpio)

/* pc21a_ebi_a15 */
#define PC21A_EBI_A15 \
	SAM_PINMUX(c, 21, a, periph)

/* pc22_gpio */
#define PC22_GPIO \
	SAM_PINMUX(c, 22, gpio, gpio)

/* pc22a_ebi_a16 */
#define PC22A_EBI_A16 \
	SAM_PINMUX(c, 22, a, periph)

/* pc23_gpio */
#define PC23_GPIO \
	SAM_PINMUX(c, 23, gpio, gpio)

/* pc23a_ebi_a17 */
#define PC23A_EBI_A17 \
	SAM_PINMUX(c, 23, a, periph)

/* pc24_gpio */
#define PC24_GPIO \
	SAM_PINMUX(c, 24, gpio, gpio)

/* pc24a_ebi_a18 */
#define PC24A_EBI_A18 \
	SAM_PINMUX(c, 24, a, periph)

/* pc24b_pwm_pwmh0 */
#define PC24B_PWM_PWMH0 \
	SAM_PINMUX(c, 24, b, periph)

/* pc25_gpio */
#define PC25_GPIO \
	SAM_PINMUX(c, 25, gpio, gpio)

/* pc25a_ebi_a19 */
#define PC25A_EBI_A19 \
	SAM_PINMUX(c, 25, a, periph)

/* pc25b_pwm_pwmh1 */
#define PC25B_PWM_PWMH1 \
	SAM_PINMUX(c, 25, b, periph)

/* pc26_gpio */
#define PC26_GPIO \
	SAM_PINMUX(c, 26, gpio, gpio)

/* pc26a_ebi_a20 */
#define PC26A_EBI_A20 \
	SAM_PINMUX(c, 26, a, periph)

/* pc26b_pwm_pwmh2 */
#define PC26B_PWM_PWMH2 \
	SAM_PINMUX(c, 26, b, periph)

/* pc27_gpio */
#define PC27_GPIO \
	SAM_PINMUX(c, 27, gpio, gpio)

/* pc27a_ebi_a23 */
#define PC27A_EBI_A23 \
	SAM_PINMUX(c, 27, a, periph)

/* pc27b_pwm_pwmh3 */
#define PC27B_PWM_PWMH3 \
	SAM_PINMUX(c, 27, b, periph)

/* pc28_gpio */
#define PC28_GPIO \
	SAM_PINMUX(c, 28, gpio, gpio)

/* pc28b_hsmci_mcda4 */
#define PC28B_HSMCI_MCDA4 \
	SAM_PINMUX(c, 28, b, periph)

/* pc28x_adc_ad4 */
#define PC28X_ADC_AD4 \
	SAM_PINMUX(c, 28, x, extra)

/* pc29_gpio */
#define PC29_GPIO \
	SAM_PINMUX(c, 29, gpio, gpio)

/* pc29a_pwm_pwml0 */
#define PC29A_PWM_PWML0 \
	SAM_PINMUX(c, 29, a, periph)

/* pc29b_hsmci_mcda5 */
#define PC29B_HSMCI_MCDA5 \
	SAM_PINMUX(c, 29, b, periph)

/* pc29x_adc_ad5 */
#define PC29X_ADC_AD5 \
	SAM_PINMUX(c, 29, x, extra)

/* pc30_gpio */
#define PC30_GPIO \
	SAM_PINMUX(c, 30, gpio, gpio)

/* pc30a_pwm_pwml1 */
#define PC30A_PWM_PWML1 \
	SAM_PINMUX(c, 30, a, periph)

/* pc30b_hsmci_mcda6 */
#define PC30B_HSMCI_MCDA6 \
	SAM_PINMUX(c, 30, b, periph)

/* pc30x_adc_ad6 */
#define PC30X_ADC_AD6 \
	SAM_PINMUX(c, 30, x, extra)

/* pc31_gpio */
#define PC31_GPIO \
	SAM_PINMUX(c, 31, gpio, gpio)

/* pc31a_pwm_pwml2 */
#define PC31A_PWM_PWML2 \
	SAM_PINMUX(c, 31, a, periph)

/* pc31b_hsmci_mcda7 */
#define PC31B_HSMCI_MCDA7 \
	SAM_PINMUX(c, 31, b, periph)

/* pc31x_adc_ad7 */
#define PC31X_ADC_AD7 \
	SAM_PINMUX(c, 31, x, extra)
