/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/* pa0_gpio */
#define PA0_GPIO \
	SAM_PINMUX(a, 0, gpio, gpio)

/* pa1_gpio */
#define PA1_GPIO \
	SAM_PINMUX(a, 1, gpio, gpio)

/* pa2_gpio */
#define PA2_GPIO \
	SAM_PINMUX(a, 2, gpio, gpio)

/* pa2a_scif_gclk0 */
#define PA2A_SCIF_GCLK0 \
	SAM_PINMUX(a, 2, a, periph)

/* pa2b_spi_npcs0 */
#define PA2B_SPI_NPCS0 \
	SAM_PINMUX(a, 2, b, periph)

/* pa2g_catb_dis */
#define PA2G_CATB_DIS \
	SAM_PINMUX(a, 2, g, periph)

/* pa3_gpio */
#define PA3_GPIO \
	SAM_PINMUX(a, 3, gpio, gpio)

/* pa3b_spi_miso */
#define PA3B_SPI_MISO \
	SAM_PINMUX(a, 3, b, periph)

/* pa4_gpio */
#define PA4_GPIO \
	SAM_PINMUX(a, 4, gpio, gpio)

/* pa4a_adcife_ad0 */
#define PA4A_ADCIFE_AD0 \
	SAM_PINMUX(a, 4, a, periph)

/* pa4b_usart0_clk */
#define PA4B_USART0_CLK \
	SAM_PINMUX(a, 4, b, periph)

/* pa4c_eic_extint2 */
#define PA4C_EIC_EXTINT2 \
	SAM_PINMUX(a, 4, c, periph)

/* pa4d_gloc_in1 */
#define PA4D_GLOC_IN1 \
	SAM_PINMUX(a, 4, d, periph)

/* pa4g_catb_sense0 */
#define PA4G_CATB_SENSE0 \
	SAM_PINMUX(a, 4, g, periph)

/* pa5_gpio */
#define PA5_GPIO \
	SAM_PINMUX(a, 5, gpio, gpio)

/* pa5a_adcife_ad1 */
#define PA5A_ADCIFE_AD1 \
	SAM_PINMUX(a, 5, a, periph)

/* pa5b_usart0_rxd */
#define PA5B_USART0_RXD \
	SAM_PINMUX(a, 5, b, periph)

/* pa5c_eic_extint3 */
#define PA5C_EIC_EXTINT3 \
	SAM_PINMUX(a, 5, c, periph)

/* pa5d_gloc_in2 */
#define PA5D_GLOC_IN2 \
	SAM_PINMUX(a, 5, d, periph)

/* pa5e_adcife_trigger */
#define PA5E_ADCIFE_TRIGGER \
	SAM_PINMUX(a, 5, e, periph)

/* pa5g_catb_sense1 */
#define PA5G_CATB_SENSE1 \
	SAM_PINMUX(a, 5, g, periph)

/* pa6_gpio */
#define PA6_GPIO \
	SAM_PINMUX(a, 6, gpio, gpio)

/* pa6a_dacc_vout */
#define PA6A_DACC_VOUT \
	SAM_PINMUX(a, 6, a, periph)

/* pa6b_usart0_rts */
#define PA6B_USART0_RTS \
	SAM_PINMUX(a, 6, b, periph)

/* pa6c_eic_extint1 */
#define PA6C_EIC_EXTINT1 \
	SAM_PINMUX(a, 6, c, periph)

/* pa6d_gloc_in0 */
#define PA6D_GLOC_IN0 \
	SAM_PINMUX(a, 6, d, periph)

/* pa6e_acifc_acan0 */
#define PA6E_ACIFC_ACAN0 \
	SAM_PINMUX(a, 6, e, periph)

/* pa6g_catb_sense2 */
#define PA6G_CATB_SENSE2 \
	SAM_PINMUX(a, 6, g, periph)

/* pa7_gpio */
#define PA7_GPIO \
	SAM_PINMUX(a, 7, gpio, gpio)

/* pa7a_adcife_ad2 */
#define PA7A_ADCIFE_AD2 \
	SAM_PINMUX(a, 7, a, periph)

/* pa7b_usart0_txd */
#define PA7B_USART0_TXD \
	SAM_PINMUX(a, 7, b, periph)

/* pa7c_eic_extint4 */
#define PA7C_EIC_EXTINT4 \
	SAM_PINMUX(a, 7, c, periph)

/* pa7d_gloc_in3 */
#define PA7D_GLOC_IN3 \
	SAM_PINMUX(a, 7, d, periph)

/* pa7e_acifc_acap0 */
#define PA7E_ACIFC_ACAP0 \
	SAM_PINMUX(a, 7, e, periph)

/* pa7g_catb_sense3 */
#define PA7G_CATB_SENSE3 \
	SAM_PINMUX(a, 7, g, periph)

/* pa8_gpio */
#define PA8_GPIO \
	SAM_PINMUX(a, 8, gpio, gpio)

/* pa8a_usart0_rts */
#define PA8A_USART0_RTS \
	SAM_PINMUX(a, 8, a, periph)

/* pa8b_tc0_a0 */
#define PA8B_TC0_A0 \
	SAM_PINMUX(a, 8, b, periph)

/* pa8c_pevc_evt0 */
#define PA8C_PEVC_EVT0 \
	SAM_PINMUX(a, 8, c, periph)

/* pa8d_gloc_out0 */
#define PA8D_GLOC_OUT0 \
	SAM_PINMUX(a, 8, d, periph)

/* pa8f_lcdca_seg23 */
#define PA8F_LCDCA_SEG23 \
	SAM_PINMUX(a, 8, f, periph)

/* pa8g_catb_sense4 */
#define PA8G_CATB_SENSE4 \
	SAM_PINMUX(a, 8, g, periph)

/* pa9_gpio */
#define PA9_GPIO \
	SAM_PINMUX(a, 9, gpio, gpio)

/* pa9a_usart0_cts */
#define PA9A_USART0_CTS \
	SAM_PINMUX(a, 9, a, periph)

/* pa9b_tc0_b0 */
#define PA9B_TC0_B0 \
	SAM_PINMUX(a, 9, b, periph)

/* pa9c_pevc_evt1 */
#define PA9C_PEVC_EVT1 \
	SAM_PINMUX(a, 9, c, periph)

/* pa9d_parc_pcdata0 */
#define PA9D_PARC_PCDATA0 \
	SAM_PINMUX(a, 9, d, periph)

/* pa9f_lcdca_com3 */
#define PA9F_LCDCA_COM3 \
	SAM_PINMUX(a, 9, f, periph)

/* pa9g_catb_sense5 */
#define PA9G_CATB_SENSE5 \
	SAM_PINMUX(a, 9, g, periph)

/* pa10_gpio */
#define PA10_GPIO \
	SAM_PINMUX(a, 10, gpio, gpio)

/* pa10a_usart0_clk */
#define PA10A_USART0_CLK \
	SAM_PINMUX(a, 10, a, periph)

/* pa10b_tc0_a1 */
#define PA10B_TC0_A1 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10c_pevc_evt2 */
#define PA10C_PEVC_EVT2 \
	SAM_PINMUX(a, 10, c, periph)

/* pa10d_parc_pcdata1 */
#define PA10D_PARC_PCDATA1 \
	SAM_PINMUX(a, 10, d, periph)

/* pa10f_lcdca_com2 */
#define PA10F_LCDCA_COM2 \
	SAM_PINMUX(a, 10, f, periph)

/* pa10g_catb_sense6 */
#define PA10G_CATB_SENSE6 \
	SAM_PINMUX(a, 10, g, periph)

/* pa11_gpio */
#define PA11_GPIO \
	SAM_PINMUX(a, 11, gpio, gpio)

/* pa11a_usart0_rxd */
#define PA11A_USART0_RXD \
	SAM_PINMUX(a, 11, a, periph)

/* pa11b_tc0_b1 */
#define PA11B_TC0_B1 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11c_pevc_evt3 */
#define PA11C_PEVC_EVT3 \
	SAM_PINMUX(a, 11, c, periph)

/* pa11d_parc_pcdata2 */
#define PA11D_PARC_PCDATA2 \
	SAM_PINMUX(a, 11, d, periph)

/* pa11f_lcdca_com1 */
#define PA11F_LCDCA_COM1 \
	SAM_PINMUX(a, 11, f, periph)

/* pa11g_catb_sense7 */
#define PA11G_CATB_SENSE7 \
	SAM_PINMUX(a, 11, g, periph)

/* pa12_gpio */
#define PA12_GPIO \
	SAM_PINMUX(a, 12, gpio, gpio)

/* pa12a_usart0_txd */
#define PA12A_USART0_TXD \
	SAM_PINMUX(a, 12, a, periph)

/* pa12b_tc0_a2 */
#define PA12B_TC0_A2 \
	SAM_PINMUX(a, 12, b, periph)

/* pa12d_parc_pcdata3 */
#define PA12D_PARC_PCDATA3 \
	SAM_PINMUX(a, 12, d, periph)

/* pa12f_lcdca_com0 */
#define PA12F_LCDCA_COM0 \
	SAM_PINMUX(a, 12, f, periph)

/* pa12g_catb_dis */
#define PA12G_CATB_DIS \
	SAM_PINMUX(a, 12, g, periph)

/* pa13_gpio */
#define PA13_GPIO \
	SAM_PINMUX(a, 13, gpio, gpio)

/* pa13a_usart1_rts */
#define PA13A_USART1_RTS \
	SAM_PINMUX(a, 13, a, periph)

/* pa13b_tc0_b2 */
#define PA13B_TC0_B2 \
	SAM_PINMUX(a, 13, b, periph)

/* pa13c_spi_npcs1 */
#define PA13C_SPI_NPCS1 \
	SAM_PINMUX(a, 13, c, periph)

/* pa13d_parc_pcdata4 */
#define PA13D_PARC_PCDATA4 \
	SAM_PINMUX(a, 13, d, periph)

/* pa13f_lcdca_seg5 */
#define PA13F_LCDCA_SEG5 \
	SAM_PINMUX(a, 13, f, periph)

/* pa13g_catb_sense8 */
#define PA13G_CATB_SENSE8 \
	SAM_PINMUX(a, 13, g, periph)

/* pa14_gpio */
#define PA14_GPIO \
	SAM_PINMUX(a, 14, gpio, gpio)

/* pa14a_usart1_clk */
#define PA14A_USART1_CLK \
	SAM_PINMUX(a, 14, a, periph)

/* pa14b_tc0_clk0 */
#define PA14B_TC0_CLK0 \
	SAM_PINMUX(a, 14, b, periph)

/* pa14c_spi_npcs2 */
#define PA14C_SPI_NPCS2 \
	SAM_PINMUX(a, 14, c, periph)

/* pa14d_parc_pcdata5 */
#define PA14D_PARC_PCDATA5 \
	SAM_PINMUX(a, 14, d, periph)

/* pa14f_lcdca_seg6 */
#define PA14F_LCDCA_SEG6 \
	SAM_PINMUX(a, 14, f, periph)

/* pa14g_catb_sense9 */
#define PA14G_CATB_SENSE9 \
	SAM_PINMUX(a, 14, g, periph)

/* pa15_gpio */
#define PA15_GPIO \
	SAM_PINMUX(a, 15, gpio, gpio)

/* pa15a_usart1_rxd */
#define PA15A_USART1_RXD \
	SAM_PINMUX(a, 15, a, periph)

/* pa15b_tc0_clk1 */
#define PA15B_TC0_CLK1 \
	SAM_PINMUX(a, 15, b, periph)

/* pa15c_spi_npcs3 */
#define PA15C_SPI_NPCS3 \
	SAM_PINMUX(a, 15, c, periph)

/* pa15d_parc_pcdata6 */
#define PA15D_PARC_PCDATA6 \
	SAM_PINMUX(a, 15, d, periph)

/* pa15f_lcdca_seg7 */
#define PA15F_LCDCA_SEG7 \
	SAM_PINMUX(a, 15, f, periph)

/* pa15g_catb_sense10 */
#define PA15G_CATB_SENSE10 \
	SAM_PINMUX(a, 15, g, periph)

/* pa16_gpio */
#define PA16_GPIO \
	SAM_PINMUX(a, 16, gpio, gpio)

/* pa16a_usart1_txd */
#define PA16A_USART1_TXD \
	SAM_PINMUX(a, 16, a, periph)

/* pa16b_tc0_clk2 */
#define PA16B_TC0_CLK2 \
	SAM_PINMUX(a, 16, b, periph)

/* pa16c_eic_extint1 */
#define PA16C_EIC_EXTINT1 \
	SAM_PINMUX(a, 16, c, periph)

/* pa16d_parc_pcdata7 */
#define PA16D_PARC_PCDATA7 \
	SAM_PINMUX(a, 16, d, periph)

/* pa16f_lcdca_seg8 */
#define PA16F_LCDCA_SEG8 \
	SAM_PINMUX(a, 16, f, periph)

/* pa16g_catb_sense11 */
#define PA16G_CATB_SENSE11 \
	SAM_PINMUX(a, 16, g, periph)

/* pa17_gpio */
#define PA17_GPIO \
	SAM_PINMUX(a, 17, gpio, gpio)

/* pa17a_usart2_rts */
#define PA17A_USART2_RTS \
	SAM_PINMUX(a, 17, a, periph)

/* pa17b_abdacb_dac0 */
#define PA17B_ABDACB_DAC0 \
	SAM_PINMUX(a, 17, b, periph)

/* pa17c_eic_extint2 */
#define PA17C_EIC_EXTINT2 \
	SAM_PINMUX(a, 17, c, periph)

/* pa17d_parc_pcck */
#define PA17D_PARC_PCCK \
	SAM_PINMUX(a, 17, d, periph)

/* pa17f_lcdca_seg9 */
#define PA17F_LCDCA_SEG9 \
	SAM_PINMUX(a, 17, f, periph)

/* pa17g_catb_sense12 */
#define PA17G_CATB_SENSE12 \
	SAM_PINMUX(a, 17, g, periph)

/* pa18_gpio */
#define PA18_GPIO \
	SAM_PINMUX(a, 18, gpio, gpio)

/* pa18a_usart2_clk */
#define PA18A_USART2_CLK \
	SAM_PINMUX(a, 18, a, periph)

/* pa18b_abdacb_dacn0 */
#define PA18B_ABDACB_DACN0 \
	SAM_PINMUX(a, 18, b, periph)

/* pa18c_eic_extint3 */
#define PA18C_EIC_EXTINT3 \
	SAM_PINMUX(a, 18, c, periph)

/* pa18d_parc_pcen1 */
#define PA18D_PARC_PCEN1 \
	SAM_PINMUX(a, 18, d, periph)

/* pa18f_lcdca_seg18 */
#define PA18F_LCDCA_SEG18 \
	SAM_PINMUX(a, 18, f, periph)

/* pa18g_catb_sense13 */
#define PA18G_CATB_SENSE13 \
	SAM_PINMUX(a, 18, g, periph)

/* pa19_gpio */
#define PA19_GPIO \
	SAM_PINMUX(a, 19, gpio, gpio)

/* pa19a_usart2_rxd */
#define PA19A_USART2_RXD \
	SAM_PINMUX(a, 19, a, periph)

/* pa19b_abdacb_dac1 */
#define PA19B_ABDACB_DAC1 \
	SAM_PINMUX(a, 19, b, periph)

/* pa19c_eic_extint4 */
#define PA19C_EIC_EXTINT4 \
	SAM_PINMUX(a, 19, c, periph)

/* pa19d_parc_pcen2 */
#define PA19D_PARC_PCEN2 \
	SAM_PINMUX(a, 19, d, periph)

/* pa19e_scif_gclk0 */
#define PA19E_SCIF_GCLK0 \
	SAM_PINMUX(a, 19, e, periph)

/* pa19f_lcdca_seg19 */
#define PA19F_LCDCA_SEG19 \
	SAM_PINMUX(a, 19, f, periph)

/* pa19g_catb_sense14 */
#define PA19G_CATB_SENSE14 \
	SAM_PINMUX(a, 19, g, periph)

/* pa20_gpio */
#define PA20_GPIO \
	SAM_PINMUX(a, 20, gpio, gpio)

/* pa20a_usart2_txd */
#define PA20A_USART2_TXD \
	SAM_PINMUX(a, 20, a, periph)

/* pa20b_abdacb_dacn1 */
#define PA20B_ABDACB_DACN1 \
	SAM_PINMUX(a, 20, b, periph)

/* pa20c_eic_extint5 */
#define PA20C_EIC_EXTINT5 \
	SAM_PINMUX(a, 20, c, periph)

/* pa20d_gcloc_in0 */
#define PA20D_GCLOC_IN0 \
	SAM_PINMUX(a, 20, d, periph)

/* pa20e_scif_gclk1 */
#define PA20E_SCIF_GCLK1 \
	SAM_PINMUX(a, 20, e, periph)

/* pa20f_lcdca_seg20 */
#define PA20F_LCDCA_SEG20 \
	SAM_PINMUX(a, 20, f, periph)

/* pa20g_catb_sense15 */
#define PA20G_CATB_SENSE15 \
	SAM_PINMUX(a, 20, g, periph)

/* pa21_gpio */
#define PA21_GPIO \
	SAM_PINMUX(a, 21, gpio, gpio)

/* pa21a_spi_miso */
#define PA21A_SPI_MISO \
	SAM_PINMUX(a, 21, a, periph)

/* pa21b_usart1_cts */
#define PA21B_USART1_CTS \
	SAM_PINMUX(a, 21, b, periph)

/* pa21c_eic_extint6 */
#define PA21C_EIC_EXTINT6 \
	SAM_PINMUX(a, 21, c, periph)

/* pa21d_gcloc_in1 */
#define PA21D_GCLOC_IN1 \
	SAM_PINMUX(a, 21, d, periph)

/* pa21e_twim2_twd */
#define PA21E_TWIM2_TWD \
	SAM_PINMUX(a, 21, e, periph)

/* pa21f_lcdca_seg34 */
#define PA21F_LCDCA_SEG34 \
	SAM_PINMUX(a, 21, f, periph)

/* pa21g_catb_sense16 */
#define PA21G_CATB_SENSE16 \
	SAM_PINMUX(a, 21, g, periph)

/* pa22_gpio */
#define PA22_GPIO \
	SAM_PINMUX(a, 22, gpio, gpio)

/* pa22a_spi_mosi */
#define PA22A_SPI_MOSI \
	SAM_PINMUX(a, 22, a, periph)

/* pa22b_usart2_cts */
#define PA22B_USART2_CTS \
	SAM_PINMUX(a, 22, b, periph)

/* pa22c_eic_extint7 */
#define PA22C_EIC_EXTINT7 \
	SAM_PINMUX(a, 22, c, periph)

/* pa22d_gcloc_in2 */
#define PA22D_GCLOC_IN2 \
	SAM_PINMUX(a, 22, d, periph)

/* pa22e_twim2_twck */
#define PA22E_TWIM2_TWCK \
	SAM_PINMUX(a, 22, e, periph)

/* pa22f_lcdca_seg35 */
#define PA22F_LCDCA_SEG35 \
	SAM_PINMUX(a, 22, f, periph)

/* pa22g_catb_sense17 */
#define PA22G_CATB_SENSE17 \
	SAM_PINMUX(a, 22, g, periph)

/* pa23_gpio */
#define PA23_GPIO \
	SAM_PINMUX(a, 23, gpio, gpio)

/* pa23a_spi_sck */
#define PA23A_SPI_SCK \
	SAM_PINMUX(a, 23, a, periph)

/* pa23b_twims0_twd */
#define PA23B_TWIMS0_TWD \
	SAM_PINMUX(a, 23, b, periph)

/* pa23c_eic_extint8 */
#define PA23C_EIC_EXTINT8 \
	SAM_PINMUX(a, 23, c, periph)

/* pa23d_gcloc_in3 */
#define PA23D_GCLOC_IN3 \
	SAM_PINMUX(a, 23, d, periph)

/* pa23e_scif_glck_in0 */
#define PA23E_SCIF_GLCK_IN0 \
	SAM_PINMUX(a, 23, e, periph)

/* pa23f_lcdca_seg38 */
#define PA23F_LCDCA_SEG38 \
	SAM_PINMUX(a, 23, f, periph)

/* pa23g_catb_dis */
#define PA23G_CATB_DIS \
	SAM_PINMUX(a, 23, g, periph)

/* pa24_gpio */
#define PA24_GPIO \
	SAM_PINMUX(a, 24, gpio, gpio)

/* pa24a_spi_npcs0 */
#define PA24A_SPI_NPCS0 \
	SAM_PINMUX(a, 24, a, periph)

/* pa24b_twims0_twck */
#define PA24B_TWIMS0_TWCK \
	SAM_PINMUX(a, 24, b, periph)

/* pa24d_gcloc_out0 */
#define PA24D_GCLOC_OUT0 \
	SAM_PINMUX(a, 24, d, periph)

/* pa24e_scif_glck_in1 */
#define PA24E_SCIF_GLCK_IN1 \
	SAM_PINMUX(a, 24, e, periph)

/* pa24f_lcdca_seg39 */
#define PA24F_LCDCA_SEG39 \
	SAM_PINMUX(a, 24, f, periph)

/* pa24g_catb_sense18 */
#define PA24G_CATB_SENSE18 \
	SAM_PINMUX(a, 24, g, periph)

/* pa25_gpio */
#define PA25_GPIO \
	SAM_PINMUX(a, 25, gpio, gpio)

/* pa25a_usbc_dm */
#define PA25A_USBC_DM \
	SAM_PINMUX(a, 25, a, periph)

/* pa25b_usart2_rxd */
#define PA25B_USART2_RXD \
	SAM_PINMUX(a, 25, b, periph)

/* pa25g_catb_sense19 */
#define PA25G_CATB_SENSE19 \
	SAM_PINMUX(a, 25, g, periph)

/* pa26_gpio */
#define PA26_GPIO \
	SAM_PINMUX(a, 26, gpio, gpio)

/* pa26a_usbc_dp */
#define PA26A_USBC_DP \
	SAM_PINMUX(a, 26, a, periph)

/* pa26b_usart2_txd */
#define PA26B_USART2_TXD \
	SAM_PINMUX(a, 26, b, periph)

/* pa26g_catb_sense20 */
#define PA26G_CATB_SENSE20 \
	SAM_PINMUX(a, 26, g, periph)

/* pa27_gpio */
#define PA27_GPIO \
	SAM_PINMUX(a, 27, gpio, gpio)

/* pa28_gpio */
#define PA28_GPIO \
	SAM_PINMUX(a, 28, gpio, gpio)

/* pa29_gpio */
#define PA29_GPIO \
	SAM_PINMUX(a, 29, gpio, gpio)

/* pa30_gpio */
#define PA30_GPIO \
	SAM_PINMUX(a, 30, gpio, gpio)

/* pa31_gpio */
#define PA31_GPIO \
	SAM_PINMUX(a, 31, gpio, gpio)
