/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/* pa0_gpio */
#define PA0_GPIO \
	SAM_PINMUX(a, 0, gpio, gpio)

/* pa0a_pwm_pwmh0 */
#define PA0A_PWM_PWMH0 \
	SAM_PINMUX(a, 0, a, periph)

/* pa0b_tc0_tioa0 */
#define PA0B_TC0_TIOA0 \
	SAM_PINMUX(a, 0, b, periph)

/* pa0x_supc_wkup0 */
#define PA0X_SUPC_WKUP0 \
	SAM_PINMUX(a, 0, wkup0, wakeup)

/* pa1_gpio */
#define PA1_GPIO \
	SAM_PINMUX(a, 1, gpio, gpio)

/* pa1a_pwm_pwmh1 */
#define PA1A_PWM_PWMH1 \
	SAM_PINMUX(a, 1, a, periph)

/* pa1b_tc0_tiob0 */
#define PA1B_TC0_TIOB0 \
	SAM_PINMUX(a, 1, b, periph)

/* pa1x_supc_wkup1 */
#define PA1X_SUPC_WKUP1 \
	SAM_PINMUX(a, 1, wkup1, wakeup)

/* pa2_gpio */
#define PA2_GPIO \
	SAM_PINMUX(a, 2, gpio, gpio)

/* pa2a_pwm_pwmh2 */
#define PA2A_PWM_PWMH2 \
	SAM_PINMUX(a, 2, a, periph)

/* pa2b_usart0_sck */
#define PA2B_USART0_SCK \
	SAM_PINMUX(a, 2, b, periph)

/* pa2c_dacc_datrg */
#define PA2C_DACC_DATRG \
	SAM_PINMUX(a, 2, c, periph)

/* pa2x_supc_wkup2 */
#define PA2X_SUPC_WKUP2 \
	SAM_PINMUX(a, 2, wkup2, wakeup)

/* pa3_gpio */
#define PA3_GPIO \
	SAM_PINMUX(a, 3, gpio, gpio)

/* pa3a_twi0_twd */
#define PA3A_TWI0_TWD \
	SAM_PINMUX(a, 3, a, periph)

/* pa3b_spi_npcs3 */
#define PA3B_SPI_NPCS3 \
	SAM_PINMUX(a, 3, b, periph)

/* pa4_gpio */
#define PA4_GPIO \
	SAM_PINMUX(a, 4, gpio, gpio)

/* pa4a_twi0_twck */
#define PA4A_TWI0_TWCK \
	SAM_PINMUX(a, 4, a, periph)

/* pa4b_tc0_tclk0 */
#define PA4B_TC0_TCLK0 \
	SAM_PINMUX(a, 4, b, periph)

/* pa4x_supc_wkup3 */
#define PA4X_SUPC_WKUP3 \
	SAM_PINMUX(a, 4, wkup3, wakeup)

/* pa5_gpio */
#define PA5_GPIO \
	SAM_PINMUX(a, 5, gpio, gpio)

/* pa5a_usart0_rxd */
#define PA5A_USART0_RXD \
	SAM_PINMUX(a, 5, a, periph)

/* pa5b_spi_npcs3 */
#define PA5B_SPI_NPCS3 \
	SAM_PINMUX(a, 5, b, periph)

/* pa5x_supc_wkup4 */
#define PA5X_SUPC_WKUP4 \
	SAM_PINMUX(a, 5, wkup4, wakeup)

/* pa6_gpio */
#define PA6_GPIO \
	SAM_PINMUX(a, 6, gpio, gpio)

/* pa6a_usart0_txd */
#define PA6A_USART0_TXD \
	SAM_PINMUX(a, 6, a, periph)

/* pa6b_pmc_pck0 */
#define PA6B_PMC_PCK0 \
	SAM_PINMUX(a, 6, b, periph)

/* pa7_gpio */
#define PA7_GPIO \
	SAM_PINMUX(a, 7, gpio, gpio)

/* pa7a_usart0_rts */
#define PA7A_USART0_RTS \
	SAM_PINMUX(a, 7, a, periph)

/* pa7b_pwm_pwmh3 */
#define PA7B_PWM_PWMH3 \
	SAM_PINMUX(a, 7, b, periph)

/* pa7s_supc_xin32 */
#define PA7S_SUPC_XIN32 \
	SAM_PINMUX(a, 7, s, system)

/* pa8_gpio */
#define PA8_GPIO \
	SAM_PINMUX(a, 8, gpio, gpio)

/* pa8a_usart0_cts */
#define PA8A_USART0_CTS \
	SAM_PINMUX(a, 8, a, periph)

/* pa8b_adc_adtrg */
#define PA8B_ADC_ADTRG \
	SAM_PINMUX(a, 8, b, periph)

/* pa8s_supc_xout32 */
#define PA8S_SUPC_XOUT32 \
	SAM_PINMUX(a, 8, s, system)

/* pa8x_supc_wkup5 */
#define PA8X_SUPC_WKUP5 \
	SAM_PINMUX(a, 8, wkup5, wakeup)

/* pa9_gpio */
#define PA9_GPIO \
	SAM_PINMUX(a, 9, gpio, gpio)

/* pa9a_uart0_rxd */
#define PA9A_UART0_RXD \
	SAM_PINMUX(a, 9, a, periph)

/* pa9b_spi_npcs1 */
#define PA9B_SPI_NPCS1 \
	SAM_PINMUX(a, 9, b, periph)

/* pa9c_pwm_pwmfi0 */
#define PA9C_PWM_PWMFI0 \
	SAM_PINMUX(a, 9, c, periph)

/* pa9x_supc_wkup6 */
#define PA9X_SUPC_WKUP6 \
	SAM_PINMUX(a, 9, wkup6, wakeup)

/* pa10_gpio */
#define PA10_GPIO \
	SAM_PINMUX(a, 10, gpio, gpio)

/* pa10a_uart0_txd */
#define PA10A_UART0_TXD \
	SAM_PINMUX(a, 10, a, periph)

/* pa10b_spi_npcs2 */
#define PA10B_SPI_NPCS2 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10c_pwm_pwmfi1 */
#define PA10C_PWM_PWMFI1 \
	SAM_PINMUX(a, 10, c, periph)

/* pa11_gpio */
#define PA11_GPIO \
	SAM_PINMUX(a, 11, gpio, gpio)

/* pa11a_spi_npcs0 */
#define PA11A_SPI_NPCS0 \
	SAM_PINMUX(a, 11, a, periph)

/* pa11b_pwm_pwmh0 */
#define PA11B_PWM_PWMH0 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11x_supc_wkup7 */
#define PA11X_SUPC_WKUP7 \
	SAM_PINMUX(a, 11, wkup7, wakeup)

/* pa12_gpio */
#define PA12_GPIO \
	SAM_PINMUX(a, 12, gpio, gpio)

/* pa12a_spi_miso */
#define PA12A_SPI_MISO \
	SAM_PINMUX(a, 12, a, periph)

/* pa12b_pwm_pwmh1 */
#define PA12B_PWM_PWMH1 \
	SAM_PINMUX(a, 12, b, periph)

/* pa13_gpio */
#define PA13_GPIO \
	SAM_PINMUX(a, 13, gpio, gpio)

/* pa13a_spi_mosi */
#define PA13A_SPI_MOSI \
	SAM_PINMUX(a, 13, a, periph)

/* pa13b_pwm_pwmh2 */
#define PA13B_PWM_PWMH2 \
	SAM_PINMUX(a, 13, b, periph)

/* pa14_gpio */
#define PA14_GPIO \
	SAM_PINMUX(a, 14, gpio, gpio)

/* pa14a_spi_spck */
#define PA14A_SPI_SPCK \
	SAM_PINMUX(a, 14, a, periph)

/* pa14b_pwm_pwmh3 */
#define PA14B_PWM_PWMH3 \
	SAM_PINMUX(a, 14, b, periph)

/* pa14x_supc_wkup8 */
#define PA14X_SUPC_WKUP8 \
	SAM_PINMUX(a, 14, wkup8, wakeup)

/* pa15_gpio */
#define PA15_GPIO \
	SAM_PINMUX(a, 15, gpio, gpio)

/* pa15a_ssc_tf */
#define PA15A_SSC_TF \
	SAM_PINMUX(a, 15, a, periph)

/* pa15b_tc0_tioa1 */
#define PA15B_TC0_TIOA1 \
	SAM_PINMUX(a, 15, b, periph)

/* pa15c_pwm_pwml3 */
#define PA15C_PWM_PWML3 \
	SAM_PINMUX(a, 15, c, periph)

/* pa15x_pio_piodcen1 */
#define PA15X_PIO_PIODCEN1 \
	SAM_PINMUX(a, 15, x, extra)

/* pa15x_supc_wkup14 */
#define PA15X_SUPC_WKUP14 \
	SAM_PINMUX(a, 15, wkup14, wakeup)

/* pa16_gpio */
#define PA16_GPIO \
	SAM_PINMUX(a, 16, gpio, gpio)

/* pa16a_ssc_tk */
#define PA16A_SSC_TK \
	SAM_PINMUX(a, 16, a, periph)

/* pa16b_tc0_tiob1 */
#define PA16B_TC0_TIOB1 \
	SAM_PINMUX(a, 16, b, periph)

/* pa16c_pwm_pwml2 */
#define PA16C_PWM_PWML2 \
	SAM_PINMUX(a, 16, c, periph)

/* pa16x_pio_piodcen2 */
#define PA16X_PIO_PIODCEN2 \
	SAM_PINMUX(a, 16, x, extra)

/* pa16x_supc_wkup15 */
#define PA16X_SUPC_WKUP15 \
	SAM_PINMUX(a, 16, wkup15, wakeup)

/* pa17_gpio */
#define PA17_GPIO \
	SAM_PINMUX(a, 17, gpio, gpio)

/* pa17a_ssc_td */
#define PA17A_SSC_TD \
	SAM_PINMUX(a, 17, a, periph)

/* pa17b_pmc_pck1 */
#define PA17B_PMC_PCK1 \
	SAM_PINMUX(a, 17, b, periph)

/* pa17c_pwm_pwmh3 */
#define PA17C_PWM_PWMH3 \
	SAM_PINMUX(a, 17, c, periph)

/* pa17x_adc_ad0 */
#define PA17X_ADC_AD0 \
	SAM_PINMUX(a, 17, x, extra)

/* pa18_gpio */
#define PA18_GPIO \
	SAM_PINMUX(a, 18, gpio, gpio)

/* pa18a_ssc_rd */
#define PA18A_SSC_RD \
	SAM_PINMUX(a, 18, a, periph)

/* pa18b_pmc_pck2 */
#define PA18B_PMC_PCK2 \
	SAM_PINMUX(a, 18, b, periph)

/* pa18d_pwm_pwmfi2 */
#define PA18D_PWM_PWMFI2 \
	SAM_PINMUX(a, 18, d, periph)

/* pa18x_adc_ad1 */
#define PA18X_ADC_AD1 \
	SAM_PINMUX(a, 18, x, extra)

/* pa19_gpio */
#define PA19_GPIO \
	SAM_PINMUX(a, 19, gpio, gpio)

/* pa19a_ssc_rk */
#define PA19A_SSC_RK \
	SAM_PINMUX(a, 19, a, periph)

/* pa19b_pwm_pwml0 */
#define PA19B_PWM_PWML0 \
	SAM_PINMUX(a, 19, b, periph)

/* pa19x_adc_ad2 */
#define PA19X_ADC_AD2 \
	SAM_PINMUX(a, 19, x, extra)

/* pa19x_supc_wkup9 */
#define PA19X_SUPC_WKUP9 \
	SAM_PINMUX(a, 19, wkup9, wakeup)

/* pa20_gpio */
#define PA20_GPIO \
	SAM_PINMUX(a, 20, gpio, gpio)

/* pa20a_ssc_rf */
#define PA20A_SSC_RF \
	SAM_PINMUX(a, 20, a, periph)

/* pa20b_pwm_pwml1 */
#define PA20B_PWM_PWML1 \
	SAM_PINMUX(a, 20, b, periph)

/* pa20x_adc_ad3 */
#define PA20X_ADC_AD3 \
	SAM_PINMUX(a, 20, x, extra)

/* pa20x_supc_wkup10 */
#define PA20X_SUPC_WKUP10 \
	SAM_PINMUX(a, 20, wkup10, wakeup)

/* pa21_gpio */
#define PA21_GPIO \
	SAM_PINMUX(a, 21, gpio, gpio)

/* pa21a_usart1_rxd */
#define PA21A_USART1_RXD \
	SAM_PINMUX(a, 21, a, periph)

/* pa21b_pmc_pck1 */
#define PA21B_PMC_PCK1 \
	SAM_PINMUX(a, 21, b, periph)

/* pa21x_adc_ad8 */
#define PA21X_ADC_AD8 \
	SAM_PINMUX(a, 21, x, extra)

/* pa22_gpio */
#define PA22_GPIO \
	SAM_PINMUX(a, 22, gpio, gpio)

/* pa22a_usart1_txd */
#define PA22A_USART1_TXD \
	SAM_PINMUX(a, 22, a, periph)

/* pa22b_spi_npcs3 */
#define PA22B_SPI_NPCS3 \
	SAM_PINMUX(a, 22, b, periph)

/* pa22x_adc_ad9 */
#define PA22X_ADC_AD9 \
	SAM_PINMUX(a, 22, x, extra)

/* pa23_gpio */
#define PA23_GPIO \
	SAM_PINMUX(a, 23, gpio, gpio)

/* pa23a_usart1_sck */
#define PA23A_USART1_SCK \
	SAM_PINMUX(a, 23, a, periph)

/* pa23b_pwm_pwmh0 */
#define PA23B_PWM_PWMH0 \
	SAM_PINMUX(a, 23, b, periph)

/* pa23x_pio_piodcclk */
#define PA23X_PIO_PIODCCLK \
	SAM_PINMUX(a, 23, x, extra)

/* pa24_gpio */
#define PA24_GPIO \
	SAM_PINMUX(a, 24, gpio, gpio)

/* pa24a_usart1_rts */
#define PA24A_USART1_RTS \
	SAM_PINMUX(a, 24, a, periph)

/* pa24b_pwm_pwmh1 */
#define PA24B_PWM_PWMH1 \
	SAM_PINMUX(a, 24, b, periph)

/* pa24x_pio_piodc0 */
#define PA24X_PIO_PIODC0 \
	SAM_PINMUX(a, 24, x, extra)

/* pa25_gpio */
#define PA25_GPIO \
	SAM_PINMUX(a, 25, gpio, gpio)

/* pa25a_usart1_cts */
#define PA25A_USART1_CTS \
	SAM_PINMUX(a, 25, a, periph)

/* pa25b_pwm_pwmh2 */
#define PA25B_PWM_PWMH2 \
	SAM_PINMUX(a, 25, b, periph)

/* pa25x_pio_piodc1 */
#define PA25X_PIO_PIODC1 \
	SAM_PINMUX(a, 25, x, extra)

/* pa26_gpio */
#define PA26_GPIO \
	SAM_PINMUX(a, 26, gpio, gpio)

/* pa26a_usart1_dcd */
#define PA26A_USART1_DCD \
	SAM_PINMUX(a, 26, a, periph)

/* pa26b_tc02_tioa2 */
#define PA26B_TC02_TIOA2 \
	SAM_PINMUX(a, 26, b, periph)

/* pa26c_hsmci_mcda2 */
#define PA26C_HSMCI_MCDA2 \
	SAM_PINMUX(a, 26, c, periph)

/* pa26x_pio_piodc2 */
#define PA26X_PIO_PIODC2 \
	SAM_PINMUX(a, 26, x, extra)

/* pa27_gpio */
#define PA27_GPIO \
	SAM_PINMUX(a, 27, gpio, gpio)

/* pa27a_usart1_dtr */
#define PA27A_USART1_DTR \
	SAM_PINMUX(a, 27, a, periph)

/* pa27b_tc0_tiob2 */
#define PA27B_TC0_TIOB2 \
	SAM_PINMUX(a, 27, b, periph)

/* pa27c_hsmci_mcda3 */
#define PA27C_HSMCI_MCDA3 \
	SAM_PINMUX(a, 27, c, periph)

/* pa27x_pio_piodc3 */
#define PA27X_PIO_PIODC3 \
	SAM_PINMUX(a, 27, x, extra)

/* pa28_gpio */
#define PA28_GPIO \
	SAM_PINMUX(a, 28, gpio, gpio)

/* pa28a_usart1_dsr */
#define PA28A_USART1_DSR \
	SAM_PINMUX(a, 28, a, periph)

/* pa28b_tc0_tclk1 */
#define PA28B_TC0_TCLK1 \
	SAM_PINMUX(a, 28, b, periph)

/* pa28c_hsmci_mccda */
#define PA28C_HSMCI_MCCDA \
	SAM_PINMUX(a, 28, c, periph)

/* pa28x_pio_piodc4 */
#define PA28X_PIO_PIODC4 \
	SAM_PINMUX(a, 28, x, extra)

/* pa29_gpio */
#define PA29_GPIO \
	SAM_PINMUX(a, 29, gpio, gpio)

/* pa29a_usart1_ri1 */
#define PA29A_USART1_RI1 \
	SAM_PINMUX(a, 29, a, periph)

/* pa29b_tc0_tclk2 */
#define PA29B_TC0_TCLK2 \
	SAM_PINMUX(a, 29, b, periph)

/* pa29c_hsmci_mcck */
#define PA29C_HSMCI_MCCK \
	SAM_PINMUX(a, 29, c, periph)

/* pa29x_pio_piodc5 */
#define PA29X_PIO_PIODC5 \
	SAM_PINMUX(a, 29, x, extra)

/* pa30_gpio */
#define PA30_GPIO \
	SAM_PINMUX(a, 30, gpio, gpio)

/* pa30a_pwm_pwml2 */
#define PA30A_PWM_PWML2 \
	SAM_PINMUX(a, 30, a, periph)

/* pa30b_spi_npcs2 */
#define PA30B_SPI_NPCS2 \
	SAM_PINMUX(a, 30, b, periph)

/* pa30c_hsmci_mcda0 */
#define PA30C_HSMCI_MCDA0 \
	SAM_PINMUX(a, 30, c, periph)

/* pa30x_pio_piodc6 */
#define PA30X_PIO_PIODC6 \
	SAM_PINMUX(a, 30, x, extra)

/* pa30x_supc_wkup11 */
#define PA30X_SUPC_WKUP11 \
	SAM_PINMUX(a, 30, wkup11, wakeup)

/* pa31_gpio */
#define PA31_GPIO \
	SAM_PINMUX(a, 31, gpio, gpio)

/* pa31a_spi_npcs1 */
#define PA31A_SPI_NPCS1 \
	SAM_PINMUX(a, 31, a, periph)

/* pa31b_pmc_pck2 */
#define PA31B_PMC_PCK2 \
	SAM_PINMUX(a, 31, b, periph)

/* pa31c_hsmci_mcda1 */
#define PA31C_HSMCI_MCDA1 \
	SAM_PINMUX(a, 31, c, periph)

/* pa31x_pio_piodc7 */
#define PA31X_PIO_PIODC7 \
	SAM_PINMUX(a, 31, x, extra)

/* pb0_gpio */
#define PB0_GPIO \
	SAM_PINMUX(b, 0, gpio, gpio)

/* pb0a_pwm_pwmh0 */
#define PB0A_PWM_PWMH0 \
	SAM_PINMUX(b, 0, a, periph)

/* pb0x_adc_ad4 */
#define PB0X_ADC_AD4 \
	SAM_PINMUX(b, 0, x, extra)

/* pb0x_rtc_out0 */
#define PB0X_RTC_OUT0 \
	SAM_PINMUX(b, 0, x, extra)

/* pb1_gpio */
#define PB1_GPIO \
	SAM_PINMUX(b, 1, gpio, gpio)

/* pb1a_pwm_pwmh1 */
#define PB1A_PWM_PWMH1 \
	SAM_PINMUX(b, 1, a, periph)

/* pb1x_adc_ad5 */
#define PB1X_ADC_AD5 \
	SAM_PINMUX(b, 1, x, extra)

/* pb1x_rtc_out1 */
#define PB1X_RTC_OUT1 \
	SAM_PINMUX(b, 1, x, extra)

/* pb2_gpio */
#define PB2_GPIO \
	SAM_PINMUX(b, 2, gpio, gpio)

/* pb2a_uart1_rxd */
#define PB2A_UART1_RXD \
	SAM_PINMUX(b, 2, a, periph)

/* pb2b_spi_npcs2 */
#define PB2B_SPI_NPCS2 \
	SAM_PINMUX(b, 2, b, periph)

/* pb2x_adc_ad6 */
#define PB2X_ADC_AD6 \
	SAM_PINMUX(b, 2, x, extra)

/* pb2x_supc_wkup12 */
#define PB2X_SUPC_WKUP12 \
	SAM_PINMUX(b, 2, wkup12, wakeup)

/* pb3_gpio */
#define PB3_GPIO \
	SAM_PINMUX(b, 3, gpio, gpio)

/* pb3a_uart1_txd */
#define PB3A_UART1_TXD \
	SAM_PINMUX(b, 3, a, periph)

/* pb3b_pmc_pck2 */
#define PB3B_PMC_PCK2 \
	SAM_PINMUX(b, 3, b, periph)

/* pb3x_adc_ad7 */
#define PB3X_ADC_AD7 \
	SAM_PINMUX(b, 3, x, extra)

/* pb4_gpio */
#define PB4_GPIO \
	SAM_PINMUX(b, 4, gpio, gpio)

/* pb4a_twi1_twd */
#define PB4A_TWI1_TWD \
	SAM_PINMUX(b, 4, a, periph)

/* pb4b_pwm_pwmh2 */
#define PB4B_PWM_PWMH2 \
	SAM_PINMUX(b, 4, b, periph)

/* pb4s_jtag_tdi */
#define PB4S_JTAG_TDI \
	SAM_PINMUX(b, 4, s, system)

/* pb5_gpio */
#define PB5_GPIO \
	SAM_PINMUX(b, 5, gpio, gpio)

/* pb5a_twi1_twck */
#define PB5A_TWI1_TWCK \
	SAM_PINMUX(b, 5, a, periph)

/* pb5b_pwm_pwml0 */
#define PB5B_PWM_PWML0 \
	SAM_PINMUX(b, 5, b, periph)

/* pb5s_jtag_tdo */
#define PB5S_JTAG_TDO \
	SAM_PINMUX(b, 5, s, system)

/* pb5s_swd_traceswo */
#define PB5S_SWD_TRACESWO \
	SAM_PINMUX(b, 5, s, system)

/* pb5x_supc_wkup13 */
#define PB5X_SUPC_WKUP13 \
	SAM_PINMUX(b, 5, wkup13, wakeup)

/* pb6_gpio */
#define PB6_GPIO \
	SAM_PINMUX(b, 6, gpio, gpio)

/* pb6s_jtag_tms */
#define PB6S_JTAG_TMS \
	SAM_PINMUX(b, 6, s, system)

/* pb6s_swd_swdio */
#define PB6S_SWD_SWDIO \
	SAM_PINMUX(b, 6, s, system)

/* pb7_gpio */
#define PB7_GPIO \
	SAM_PINMUX(b, 7, gpio, gpio)

/* pb7s_jtag_tck */
#define PB7S_JTAG_TCK \
	SAM_PINMUX(b, 7, s, system)

/* pb7s_swd_swclk */
#define PB7S_SWD_SWCLK \
	SAM_PINMUX(b, 7, s, system)

/* pb8_gpio */
#define PB8_GPIO \
	SAM_PINMUX(b, 8, gpio, gpio)

/* pb8s_supc_xout */
#define PB8S_SUPC_XOUT \
	SAM_PINMUX(b, 8, s, system)

/* pb9_gpio */
#define PB9_GPIO \
	SAM_PINMUX(b, 9, gpio, gpio)

/* pb9s_supc_xin */
#define PB9S_SUPC_XIN \
	SAM_PINMUX(b, 9, s, system)

/* pb10_gpio */
#define PB10_GPIO \
	SAM_PINMUX(b, 10, gpio, gpio)

/* pb10s_udp_ddm */
#define PB10S_UDP_DDM \
	SAM_PINMUX(b, 10, s, system)

/* pb11_gpio */
#define PB11_GPIO \
	SAM_PINMUX(b, 11, gpio, gpio)

/* pb11s_udp_ddp */
#define PB11S_UDP_DDP \
	SAM_PINMUX(b, 11, s, system)

/* pb12_gpio */
#define PB12_GPIO \
	SAM_PINMUX(b, 12, gpio, gpio)

/* pb12a_pwm_pwml1 */
#define PB12A_PWM_PWML1 \
	SAM_PINMUX(b, 12, a, periph)

/* pb12s_flash_erase */
#define PB12S_FLASH_ERASE \
	SAM_PINMUX(b, 12, s, system)

/* pb13_gpio */
#define PB13_GPIO \
	SAM_PINMUX(b, 13, gpio, gpio)

/* pb13a_pwm_pwml2 */
#define PB13A_PWM_PWML2 \
	SAM_PINMUX(b, 13, a, periph)

/* pb13b_pmc_pck0 */
#define PB13B_PMC_PCK0 \
	SAM_PINMUX(b, 13, b, periph)

/* pb13d_dacc_dac0 */
#define PB13D_DACC_DAC0 \
	SAM_PINMUX(b, 13, d, periph)

/* pb14_gpio */
#define PB14_GPIO \
	SAM_PINMUX(b, 14, gpio, gpio)

/* pb14a_spi_npcs1 */
#define PB14A_SPI_NPCS1 \
	SAM_PINMUX(b, 14, a, periph)

/* pb14b_pwm_pwmh3 */
#define PB14B_PWM_PWMH3 \
	SAM_PINMUX(b, 14, b, periph)

/* pb14d_dacc_dac1 */
#define PB14D_DACC_DAC1 \
	SAM_PINMUX(b, 14, d, periph)
