/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/* pa2_gpio */
#define PA2_GPIO \
	SAM_PINMUX(a, 2, gpio, gpio)

/* pa2a_eic_extint2 */
#define PA2A_EIC_EXTINT2 \
	SAM_PINMUX(a, 2, a, periph)

/* pa2b_adc_ain0 */
#define PA2B_ADC_AIN0 \
	SAM_PINMUX(a, 2, b, periph)

/* pa2b_ptc_y0 */
#define PA2B_PTC_Y0 \
	SAM_PINMUX(a, 2, b, periph)

/* pa2b_dac_vout */
#define PA2B_DAC_VOUT \
	SAM_PINMUX(a, 2, b, periph)

/* pa3_gpio */
#define PA3_GPIO \
	SAM_PINMUX(a, 3, gpio, gpio)

/* pa3a_eic_extint3 */
#define PA3A_EIC_EXTINT3 \
	SAM_PINMUX(a, 3, a, periph)

/* pa3b_adc_dac_vrefa */
#define PA3B_ADC_DAC_VREFA \
	SAM_PINMUX(a, 3, b, periph)

/* pa3b_adc_ain1 */
#define PA3B_ADC_AIN1 \
	SAM_PINMUX(a, 3, b, periph)

/* pa3b_ptc_y1 */
#define PA3B_PTC_Y1 \
	SAM_PINMUX(a, 3, b, periph)

/* pa4_gpio */
#define PA4_GPIO \
	SAM_PINMUX(a, 4, gpio, gpio)

/* pa4a_eic_extint4 */
#define PA4A_EIC_EXTINT4 \
	SAM_PINMUX(a, 4, a, periph)

/* pa4b_adc_vrefb */
#define PA4B_ADC_VREFB \
	SAM_PINMUX(a, 4, b, periph)

/* pa4b_adc_ain2 */
#define PA4B_ADC_AIN2 \
	SAM_PINMUX(a, 4, b, periph)

/* pa4b_ac_ain0 */
#define PA4B_AC_AIN0 \
	SAM_PINMUX(a, 4, b, periph)

/* pa4b_ptc_y2 */
#define PA4B_PTC_Y2 \
	SAM_PINMUX(a, 4, b, periph)

/* pa4c_sercom0_pad2 */
#define PA4C_SERCOM0_PAD2 \
	SAM_PINMUX(a, 4, c, periph)

/* pa4d_sercom0_pad0 */
#define PA4D_SERCOM0_PAD0 \
	SAM_PINMUX(a, 4, d, periph)

/* pa4e_tc1_wo0 */
#define PA4E_TC1_WO0 \
	SAM_PINMUX(a, 4, e, periph)

/* pa4f_tcc0_wo0 */
#define PA4F_TCC0_WO0 \
	SAM_PINMUX(a, 4, f, periph)

/* pa5_gpio */
#define PA5_GPIO \
	SAM_PINMUX(a, 5, gpio, gpio)

/* pa5a_eic_extint5 */
#define PA5A_EIC_EXTINT5 \
	SAM_PINMUX(a, 5, a, periph)

/* pa5b_adc_ain3 */
#define PA5B_ADC_AIN3 \
	SAM_PINMUX(a, 5, b, periph)

/* pa5b_ac_ain1 */
#define PA5B_AC_AIN1 \
	SAM_PINMUX(a, 5, b, periph)

/* pa5b_ptc_y3 */
#define PA5B_PTC_Y3 \
	SAM_PINMUX(a, 5, b, periph)

/* pa5c_sercom0_pad3 */
#define PA5C_SERCOM0_PAD3 \
	SAM_PINMUX(a, 5, c, periph)

/* pa5d_sercom0_pad1 */
#define PA5D_SERCOM0_PAD1 \
	SAM_PINMUX(a, 5, d, periph)

/* pa5e_tc1_wo1 */
#define PA5E_TC1_WO1 \
	SAM_PINMUX(a, 5, e, periph)

/* pa5f_tcc0_wo1 */
#define PA5F_TCC0_WO1 \
	SAM_PINMUX(a, 5, f, periph)

/* pa6_gpio */
#define PA6_GPIO \
	SAM_PINMUX(a, 6, gpio, gpio)

/* pa6a_eic_extint6 */
#define PA6A_EIC_EXTINT6 \
	SAM_PINMUX(a, 6, a, periph)

/* pa6b_adc_ain4 */
#define PA6B_ADC_AIN4 \
	SAM_PINMUX(a, 6, b, periph)

/* pa6b_ac_ain2 */
#define PA6B_AC_AIN2 \
	SAM_PINMUX(a, 6, b, periph)

/* pa6b_ptc_y4 */
#define PA6B_PTC_Y4 \
	SAM_PINMUX(a, 6, b, periph)

/* pa6c_sercom0_pad0 */
#define PA6C_SERCOM0_PAD0 \
	SAM_PINMUX(a, 6, c, periph)

/* pa6d_sercom0_pad2 */
#define PA6D_SERCOM0_PAD2 \
	SAM_PINMUX(a, 6, d, periph)

/* pa6e_tc2_wo0 */
#define PA6E_TC2_WO0 \
	SAM_PINMUX(a, 6, e, periph)

/* pa6f_tcc0_wo2 */
#define PA6F_TCC0_WO2 \
	SAM_PINMUX(a, 6, f, periph)

/* pa7_gpio */
#define PA7_GPIO \
	SAM_PINMUX(a, 7, gpio, gpio)

/* pa7a_eic_extint7 */
#define PA7A_EIC_EXTINT7 \
	SAM_PINMUX(a, 7, a, periph)

/* pa7b_adc_ain5 */
#define PA7B_ADC_AIN5 \
	SAM_PINMUX(a, 7, b, periph)

/* pa7b_ac_ain3 */
#define PA7B_AC_AIN3 \
	SAM_PINMUX(a, 7, b, periph)

/* pa7b_ptc_y5 */
#define PA7B_PTC_Y5 \
	SAM_PINMUX(a, 7, b, periph)

/* pa7c_sercom0_pad1 */
#define PA7C_SERCOM0_PAD1 \
	SAM_PINMUX(a, 7, c, periph)

/* pa7d_sercom0_pad3 */
#define PA7D_SERCOM0_PAD3 \
	SAM_PINMUX(a, 7, d, periph)

/* pa7e_tc2_wo1 */
#define PA7E_TC2_WO1 \
	SAM_PINMUX(a, 7, e, periph)

/* pa7f_tcc0_wo3 */
#define PA7F_TCC0_WO3 \
	SAM_PINMUX(a, 7, f, periph)

/* pa8_gpio */
#define PA8_GPIO \
	SAM_PINMUX(a, 8, gpio, gpio)

/* pa8a_eic_extint6 */
#define PA8A_EIC_EXTINT6 \
	SAM_PINMUX(a, 8, a, periph)

/* pa8c_sercom1_pad2 */
#define PA8C_SERCOM1_PAD2 \
	SAM_PINMUX(a, 8, c, periph)

/* pa8d_sercom0_pad2 */
#define PA8D_SERCOM0_PAD2 \
	SAM_PINMUX(a, 8, d, periph)

/* pa8e_tcc0_wo2 */
#define PA8E_TCC0_WO2 \
	SAM_PINMUX(a, 8, e, periph)

/* pa8f_tcc0_wo4 */
#define PA8F_TCC0_WO4 \
	SAM_PINMUX(a, 8, f, periph)

/* pa8h_gclk_io0 */
#define PA8H_GCLK_IO0 \
	SAM_PINMUX(a, 8, h, periph)

/* pa9_gpio */
#define PA9_GPIO \
	SAM_PINMUX(a, 9, gpio, gpio)

/* pa9a_eic_extint7 */
#define PA9A_EIC_EXTINT7 \
	SAM_PINMUX(a, 9, a, periph)

/* pa9c_sercom1_pad3 */
#define PA9C_SERCOM1_PAD3 \
	SAM_PINMUX(a, 9, c, periph)

/* pa9d_sercom0_pad3 */
#define PA9D_SERCOM0_PAD3 \
	SAM_PINMUX(a, 9, d, periph)

/* pa9e_tcc0_wo3 */
#define PA9E_TCC0_WO3 \
	SAM_PINMUX(a, 9, e, periph)

/* pa9f_tcc0_wo5 */
#define PA9F_TCC0_WO5 \
	SAM_PINMUX(a, 9, f, periph)

/* pa9h_gclk_io1 */
#define PA9H_GCLK_IO1 \
	SAM_PINMUX(a, 9, h, periph)

/* pa10_gpio */
#define PA10_GPIO \
	SAM_PINMUX(a, 10, gpio, gpio)

/* pa10a_eic_extint2 */
#define PA10A_EIC_EXTINT2 \
	SAM_PINMUX(a, 10, a, periph)

/* pa10b_adc_ain8 */
#define PA10B_ADC_AIN8 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10b_ac_cmp0 */
#define PA10B_AC_CMP0 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10b_ptc_x2 */
#define PA10B_PTC_X2 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10b_ptc_y8 */
#define PA10B_PTC_Y8 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10c_sercom0_pad2 */
#define PA10C_SERCOM0_PAD2 \
	SAM_PINMUX(a, 10, c, periph)

/* pa10d_sercom2_pad2 */
#define PA10D_SERCOM2_PAD2 \
	SAM_PINMUX(a, 10, d, periph)

/* pa10e_tc2_wo0 */
#define PA10E_TC2_WO0 \
	SAM_PINMUX(a, 10, e, periph)

/* pa10f_tcc0_wo2 */
#define PA10F_TCC0_WO2 \
	SAM_PINMUX(a, 10, f, periph)

/* pa10h_gclk_io4 */
#define PA10H_GCLK_IO4 \
	SAM_PINMUX(a, 10, h, periph)

/* pa11_gpio */
#define PA11_GPIO \
	SAM_PINMUX(a, 11, gpio, gpio)

/* pa11a_eic_extint3 */
#define PA11A_EIC_EXTINT3 \
	SAM_PINMUX(a, 11, a, periph)

/* pa11b_adc_ain9 */
#define PA11B_ADC_AIN9 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11b_ac_cmp1 */
#define PA11B_AC_CMP1 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11b_ptc_x3 */
#define PA11B_PTC_X3 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11b_ptc_y9 */
#define PA11B_PTC_Y9 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11c_sercom0_pad3 */
#define PA11C_SERCOM0_PAD3 \
	SAM_PINMUX(a, 11, c, periph)

/* pa11d_sercom2_pad3 */
#define PA11D_SERCOM2_PAD3 \
	SAM_PINMUX(a, 11, d, periph)

/* pa11e_tc2_wo1 */
#define PA11E_TC2_WO1 \
	SAM_PINMUX(a, 11, e, periph)

/* pa11f_tcc0_wo3 */
#define PA11F_TCC0_WO3 \
	SAM_PINMUX(a, 11, f, periph)

/* pa11h_gclk_io5 */
#define PA11H_GCLK_IO5 \
	SAM_PINMUX(a, 11, h, periph)

/* pa14_gpio */
#define PA14_GPIO \
	SAM_PINMUX(a, 14, gpio, gpio)

/* pa14a_eic_nmi */
#define PA14A_EIC_NMI \
	SAM_PINMUX(a, 14, a, periph)

/* pa14b_adc_ain6 */
#define PA14B_ADC_AIN6 \
	SAM_PINMUX(a, 14, b, periph)

/* pa14b_ac_cmp0 */
#define PA14B_AC_CMP0 \
	SAM_PINMUX(a, 14, b, periph)

/* pa14b_ptc_x0 */
#define PA14B_PTC_X0 \
	SAM_PINMUX(a, 14, b, periph)

/* pa14b_ptc_y6 */
#define PA14B_PTC_Y6 \
	SAM_PINMUX(a, 14, b, periph)

/* pa14c_sercom0_pad0 */
#define PA14C_SERCOM0_PAD0 \
	SAM_PINMUX(a, 14, c, periph)

/* pa14d_sercom2_pad0 */
#define PA14D_SERCOM2_PAD0 \
	SAM_PINMUX(a, 14, d, periph)

/* pa14e_tc1_wo0 */
#define PA14E_TC1_WO0 \
	SAM_PINMUX(a, 14, e, periph)

/* pa14f_tcc0_wo0 */
#define PA14F_TCC0_WO0 \
	SAM_PINMUX(a, 14, f, periph)

/* pa14h_gclk_io4 */
#define PA14H_GCLK_IO4 \
	SAM_PINMUX(a, 14, h, periph)

/* pa15_gpio */
#define PA15_GPIO \
	SAM_PINMUX(a, 15, gpio, gpio)

/* pa15a_eic_extint1 */
#define PA15A_EIC_EXTINT1 \
	SAM_PINMUX(a, 15, a, periph)

/* pa15b_adc_ain7 */
#define PA15B_ADC_AIN7 \
	SAM_PINMUX(a, 15, b, periph)

/* pa15b_ac_cmp1 */
#define PA15B_AC_CMP1 \
	SAM_PINMUX(a, 15, b, periph)

/* pa15b_ptc_x1 */
#define PA15B_PTC_X1 \
	SAM_PINMUX(a, 15, b, periph)

/* pa15b_ptc_y7 */
#define PA15B_PTC_Y7 \
	SAM_PINMUX(a, 15, b, periph)

/* pa15c_sercom0_pad1 */
#define PA15C_SERCOM0_PAD1 \
	SAM_PINMUX(a, 15, c, periph)

/* pa15d_sercom2_pad1 */
#define PA15D_SERCOM2_PAD1 \
	SAM_PINMUX(a, 15, d, periph)

/* pa15e_tc1_wo1 */
#define PA15E_TC1_WO1 \
	SAM_PINMUX(a, 15, e, periph)

/* pa15f_tcc0_wo1 */
#define PA15F_TCC0_WO1 \
	SAM_PINMUX(a, 15, f, periph)

/* pa15h_gclk_io5 */
#define PA15H_GCLK_IO5 \
	SAM_PINMUX(a, 15, h, periph)

/* pa16_gpio */
#define PA16_GPIO \
	SAM_PINMUX(a, 16, gpio, gpio)

/* pa16a_eic_extint0 */
#define PA16A_EIC_EXTINT0 \
	SAM_PINMUX(a, 16, a, periph)

/* pa16b_ptc_x4 */
#define PA16B_PTC_X4 \
	SAM_PINMUX(a, 16, b, periph)

/* pa16b_ptc_y10 */
#define PA16B_PTC_Y10 \
	SAM_PINMUX(a, 16, b, periph)

/* pa16c_sercom1_pad2 */
#define PA16C_SERCOM1_PAD2 \
	SAM_PINMUX(a, 16, c, periph)

/* pa16d_sercom2_pad2 */
#define PA16D_SERCOM2_PAD2 \
	SAM_PINMUX(a, 16, d, periph)

/* pa16e_tc1_wo0 */
#define PA16E_TC1_WO0 \
	SAM_PINMUX(a, 16, e, periph)

/* pa16f_tcc0_wo6 */
#define PA16F_TCC0_WO6 \
	SAM_PINMUX(a, 16, f, periph)

/* pa16h_gclk_io2 */
#define PA16H_GCLK_IO2 \
	SAM_PINMUX(a, 16, h, periph)

/* pa17_gpio */
#define PA17_GPIO \
	SAM_PINMUX(a, 17, gpio, gpio)

/* pa17a_eic_extint1 */
#define PA17A_EIC_EXTINT1 \
	SAM_PINMUX(a, 17, a, periph)

/* pa17b_ptc_x5 */
#define PA17B_PTC_X5 \
	SAM_PINMUX(a, 17, b, periph)

/* pa17b_ptc_y11 */
#define PA17B_PTC_Y11 \
	SAM_PINMUX(a, 17, b, periph)

/* pa17c_sercom1_pad3 */
#define PA17C_SERCOM1_PAD3 \
	SAM_PINMUX(a, 17, c, periph)

/* pa17d_sercom2_pad3 */
#define PA17D_SERCOM2_PAD3 \
	SAM_PINMUX(a, 17, d, periph)

/* pa17e_tc1_wo1 */
#define PA17E_TC1_WO1 \
	SAM_PINMUX(a, 17, e, periph)

/* pa17f_tcc0_wo7 */
#define PA17F_TCC0_WO7 \
	SAM_PINMUX(a, 17, f, periph)

/* pa17h_gclk_io3 */
#define PA17H_GCLK_IO3 \
	SAM_PINMUX(a, 17, h, periph)

/* pa22_gpio */
#define PA22_GPIO \
	SAM_PINMUX(a, 22, gpio, gpio)

/* pa22a_eic_extint6 */
#define PA22A_EIC_EXTINT6 \
	SAM_PINMUX(a, 22, a, periph)

/* pa22b_ptc_x6 */
#define PA22B_PTC_X6 \
	SAM_PINMUX(a, 22, b, periph)

/* pa22b_ptc_y12 */
#define PA22B_PTC_Y12 \
	SAM_PINMUX(a, 22, b, periph)

/* pa22c_sercom1_pad0 */
#define PA22C_SERCOM1_PAD0 \
	SAM_PINMUX(a, 22, c, periph)

/* pa22d_sercom2_pad0 */
#define PA22D_SERCOM2_PAD0 \
	SAM_PINMUX(a, 22, d, periph)

/* pa22e_tc1_wo0 */
#define PA22E_TC1_WO0 \
	SAM_PINMUX(a, 22, e, periph)

/* pa22f_tcc0_wo4 */
#define PA22F_TCC0_WO4 \
	SAM_PINMUX(a, 22, f, periph)

/* pa22h_gclk_io1 */
#define PA22H_GCLK_IO1 \
	SAM_PINMUX(a, 22, h, periph)

/* pa23_gpio */
#define PA23_GPIO \
	SAM_PINMUX(a, 23, gpio, gpio)

/* pa23a_eic_extint7 */
#define PA23A_EIC_EXTINT7 \
	SAM_PINMUX(a, 23, a, periph)

/* pa23b_ptc_x7 */
#define PA23B_PTC_X7 \
	SAM_PINMUX(a, 23, b, periph)

/* pa23b_ptc_y13 */
#define PA23B_PTC_Y13 \
	SAM_PINMUX(a, 23, b, periph)

/* pa23c_sercom1_pad1 */
#define PA23C_SERCOM1_PAD1 \
	SAM_PINMUX(a, 23, c, periph)

/* pa23d_sercom2_pad1 */
#define PA23D_SERCOM2_PAD1 \
	SAM_PINMUX(a, 23, d, periph)

/* pa23e_tc1_wo1 */
#define PA23E_TC1_WO1 \
	SAM_PINMUX(a, 23, e, periph)

/* pa23f_tcc0_wo5 */
#define PA23F_TCC0_WO5 \
	SAM_PINMUX(a, 23, f, periph)

/* pa23g_usb_sof */
#define PA23G_USB_SOF \
	SAM_PINMUX(a, 23, g, periph)

/* pa23h_gclk_io2 */
#define PA23H_GCLK_IO2 \
	SAM_PINMUX(a, 23, h, periph)

/* pa24_gpio */
#define PA24_GPIO \
	SAM_PINMUX(a, 24, gpio, gpio)

/* pa24a_eic_extint4 */
#define PA24A_EIC_EXTINT4 \
	SAM_PINMUX(a, 24, a, periph)

/* pa24b_ptc_x8 */
#define PA24B_PTC_X8 \
	SAM_PINMUX(a, 24, b, periph)

/* pa24b_ptc_y14 */
#define PA24B_PTC_Y14 \
	SAM_PINMUX(a, 24, b, periph)

/* pa24c_sercom1_pad2 */
#define PA24C_SERCOM1_PAD2 \
	SAM_PINMUX(a, 24, c, periph)

/* pa24d_sercom2_pad2 */
#define PA24D_SERCOM2_PAD2 \
	SAM_PINMUX(a, 24, d, periph)

/* pa24e_tcc0_wo2 */
#define PA24E_TCC0_WO2 \
	SAM_PINMUX(a, 24, e, periph)

/* pa24f_tcc0_wo4 */
#define PA24F_TCC0_WO4 \
	SAM_PINMUX(a, 24, f, periph)

/* pa24g_usb_dm */
#define PA24G_USB_DM \
	SAM_PINMUX(a, 24, g, periph)

/* pa24h_gclk_io0 */
#define PA24H_GCLK_IO0 \
	SAM_PINMUX(a, 24, h, periph)

/* pa25_gpio */
#define PA25_GPIO \
	SAM_PINMUX(a, 25, gpio, gpio)

/* pa25a_eic_extint5 */
#define PA25A_EIC_EXTINT5 \
	SAM_PINMUX(a, 25, a, periph)

/* pa25b_ptc_x9 */
#define PA25B_PTC_X9 \
	SAM_PINMUX(a, 25, b, periph)

/* pa25b_ptc_y15 */
#define PA25B_PTC_Y15 \
	SAM_PINMUX(a, 25, b, periph)

/* pa25c_sercom1_pad3 */
#define PA25C_SERCOM1_PAD3 \
	SAM_PINMUX(a, 25, c, periph)

/* pa25d_sercom2_pad3 */
#define PA25D_SERCOM2_PAD3 \
	SAM_PINMUX(a, 25, d, periph)

/* pa25e_tcc0_wo3 */
#define PA25E_TCC0_WO3 \
	SAM_PINMUX(a, 25, e, periph)

/* pa25g_usb_dp */
#define PA25G_USB_DP \
	SAM_PINMUX(a, 25, g, periph)

/* pa25h_gclk_io0 */
#define PA25H_GCLK_IO0 \
	SAM_PINMUX(a, 25, h, periph)

/* pa27_gpio */
#define PA27_GPIO \
	SAM_PINMUX(a, 27, gpio, gpio)

/* pa27a_eic_extint7 */
#define PA27A_EIC_EXTINT7 \
	SAM_PINMUX(a, 27, a, periph)

/* pa27b_ptc_x10 */
#define PA27B_PTC_X10 \
	SAM_PINMUX(a, 27, b, periph)

/* pa27h_gclk_io0 */
#define PA27H_GCLK_IO0 \
	SAM_PINMUX(a, 27, h, periph)

/* pa30_gpio */
#define PA30_GPIO \
	SAM_PINMUX(a, 30, gpio, gpio)

/* pa30a_eic_extint2 */
#define PA30A_EIC_EXTINT2 \
	SAM_PINMUX(a, 30, a, periph)

/* pa30c_sercom1_pad0 */
#define PA30C_SERCOM1_PAD0 \
	SAM_PINMUX(a, 30, c, periph)

/* pa30d_sercom1_pad2 */
#define PA30D_SERCOM1_PAD2 \
	SAM_PINMUX(a, 30, d, periph)

/* pa30e_tc2_wo0 */
#define PA30E_TC2_WO0 \
	SAM_PINMUX(a, 30, e, periph)

/* pa30f_tcc0_wo2 */
#define PA30F_TCC0_WO2 \
	SAM_PINMUX(a, 30, f, periph)

/* pa30g_swd_clk */
#define PA30G_SWD_CLK \
	SAM_PINMUX(a, 30, g, periph)

/* pa30h_gclk_io0 */
#define PA30H_GCLK_IO0 \
	SAM_PINMUX(a, 30, h, periph)

/* pa31_gpio */
#define PA31_GPIO \
	SAM_PINMUX(a, 31, gpio, gpio)

/* pa31a_eic_extint3 */
#define PA31A_EIC_EXTINT3 \
	SAM_PINMUX(a, 31, a, periph)

/* pa31c_sercom1_pad1 */
#define PA31C_SERCOM1_PAD1 \
	SAM_PINMUX(a, 31, c, periph)

/* pa31d_sercom1_pad3 */
#define PA31D_SERCOM1_PAD3 \
	SAM_PINMUX(a, 31, d, periph)

/* pa31e_tc2_wo1 */
#define PA31E_TC2_WO1 \
	SAM_PINMUX(a, 31, e, periph)

/* pa31f_tcc3_wo3 */
#define PA31F_TCC3_WO3 \
	SAM_PINMUX(a, 31, f, periph)

/* pa31g_swd_io */
#define PA31G_SWD_IO \
	SAM_PINMUX(a, 31, g, periph)

/* pa31h_gclk_io0 */
#define PA31H_GCLK_IO0 \
	SAM_PINMUX(a, 31, h, periph)
