/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/* pa6_gpio */
#define PA6_GPIO \
	SAM_PINMUX(a, 6, gpio, gpio)

/* pa6a_eic_extint6 */
#define PA6A_EIC_EXTINT6 \
	SAM_PINMUX(a, 6, a, periph)

/* pa6b_adc_ain6 */
#define PA6B_ADC_AIN6 \
	SAM_PINMUX(a, 6, b, periph)

/* pa6b_ac_ain2 */
#define PA6B_AC_AIN2 \
	SAM_PINMUX(a, 6, b, periph)

/* pa6b_ptc_y4 */
#define PA6B_PTC_Y4 \
	SAM_PINMUX(a, 6, b, periph)

/* pa6d_sercom0_pad2 */
#define PA6D_SERCOM0_PAD2 \
	SAM_PINMUX(a, 6, d, periph)

/* pa6e_tcc1_wo0 */
#define PA6E_TCC1_WO0 \
	SAM_PINMUX(a, 6, e, periph)

/* pa7_gpio */
#define PA7_GPIO \
	SAM_PINMUX(a, 7, gpio, gpio)

/* pa7a_eic_extint7 */
#define PA7A_EIC_EXTINT7 \
	SAM_PINMUX(a, 7, a, periph)

/* pa7b_adc_ain7 */
#define PA7B_ADC_AIN7 \
	SAM_PINMUX(a, 7, b, periph)

/* pa7b_ac_ain3 */
#define PA7B_AC_AIN3 \
	SAM_PINMUX(a, 7, b, periph)

/* pa7b_ptc_y5 */
#define PA7B_PTC_Y5 \
	SAM_PINMUX(a, 7, b, periph)

/* pa7d_sercom0_pad3 */
#define PA7D_SERCOM0_PAD3 \
	SAM_PINMUX(a, 7, d, periph)

/* pa7e_tcc1_wo1 */
#define PA7E_TCC1_WO1 \
	SAM_PINMUX(a, 7, e, periph)

/* pa8_gpio */
#define PA8_GPIO \
	SAM_PINMUX(a, 8, gpio, gpio)

/* pa8a_eic_nmi */
#define PA8A_EIC_NMI \
	SAM_PINMUX(a, 8, a, periph)

/* pa8b_adc_ain16 */
#define PA8B_ADC_AIN16 \
	SAM_PINMUX(a, 8, b, periph)

/* pa8b_ptc_x0 */
#define PA8B_PTC_X0 \
	SAM_PINMUX(a, 8, b, periph)

/* pa8c_sercom0_pad0 */
#define PA8C_SERCOM0_PAD0 \
	SAM_PINMUX(a, 8, c, periph)

/* pa8d_sercom2_pad0 */
#define PA8D_SERCOM2_PAD0 \
	SAM_PINMUX(a, 8, d, periph)

/* pa8e_tcc0_wo0 */
#define PA8E_TCC0_WO0 \
	SAM_PINMUX(a, 8, e, periph)

/* pa8f_radio_fectrl0 */
#define PA8F_RADIO_FECTRL0 \
	SAM_PINMUX(a, 8, f, periph)

/* pa9_gpio */
#define PA9_GPIO \
	SAM_PINMUX(a, 9, gpio, gpio)

/* pa9a_eic_extint9 */
#define PA9A_EIC_EXTINT9 \
	SAM_PINMUX(a, 9, a, periph)

/* pa9b_adc_ain17 */
#define PA9B_ADC_AIN17 \
	SAM_PINMUX(a, 9, b, periph)

/* pa9b_ptc_x1 */
#define PA9B_PTC_X1 \
	SAM_PINMUX(a, 9, b, periph)

/* pa9c_sercom0_pad1 */
#define PA9C_SERCOM0_PAD1 \
	SAM_PINMUX(a, 9, c, periph)

/* pa9d_sercom2_pad1 */
#define PA9D_SERCOM2_PAD1 \
	SAM_PINMUX(a, 9, d, periph)

/* pa9e_tcc0_wo1 */
#define PA9E_TCC0_WO1 \
	SAM_PINMUX(a, 9, e, periph)

/* pa9f_radio_fectrl1 */
#define PA9F_RADIO_FECTRL1 \
	SAM_PINMUX(a, 9, f, periph)

/* pa10_gpio */
#define PA10_GPIO \
	SAM_PINMUX(a, 10, gpio, gpio)

/* pa10a_eic_extint10 */
#define PA10A_EIC_EXTINT10 \
	SAM_PINMUX(a, 10, a, periph)

/* pa11_gpio */
#define PA11_GPIO \
	SAM_PINMUX(a, 11, gpio, gpio)

/* pa11a_eic_extint11 */
#define PA11A_EIC_EXTINT11 \
	SAM_PINMUX(a, 11, a, periph)

/* pa14_gpio */
#define PA14_GPIO \
	SAM_PINMUX(a, 14, gpio, gpio)

/* pa14a_eic_extint14 */
#define PA14A_EIC_EXTINT14 \
	SAM_PINMUX(a, 14, a, periph)

/* pa14c_sercom2_pad2 */
#define PA14C_SERCOM2_PAD2 \
	SAM_PINMUX(a, 14, c, periph)

/* pa14e_tc3_wo0 */
#define PA14E_TC3_WO0 \
	SAM_PINMUX(a, 14, e, periph)

/* pa14f_radio_fectrl4 */
#define PA14F_RADIO_FECTRL4 \
	SAM_PINMUX(a, 14, f, periph)

/* pa14h_gclk_io0 */
#define PA14H_GCLK_IO0 \
	SAM_PINMUX(a, 14, h, periph)

/* pa15_gpio */
#define PA15_GPIO \
	SAM_PINMUX(a, 15, gpio, gpio)

/* pa15a_eic_extint15 */
#define PA15A_EIC_EXTINT15 \
	SAM_PINMUX(a, 15, a, periph)

/* pa15c_sercom2_pad3 */
#define PA15C_SERCOM2_PAD3 \
	SAM_PINMUX(a, 15, c, periph)

/* pa15e_tc3_wo1 */
#define PA15E_TC3_WO1 \
	SAM_PINMUX(a, 15, e, periph)

/* pa15f_radio_fectrl5 */
#define PA15F_RADIO_FECTRL5 \
	SAM_PINMUX(a, 15, f, periph)

/* pa15h_gclk_io1 */
#define PA15H_GCLK_IO1 \
	SAM_PINMUX(a, 15, h, periph)

/* pa16_gpio */
#define PA16_GPIO \
	SAM_PINMUX(a, 16, gpio, gpio)

/* pa16b_ptc_x4 */
#define PA16B_PTC_X4 \
	SAM_PINMUX(a, 16, b, periph)

/* pa16c_sercom1_pad0 */
#define PA16C_SERCOM1_PAD0 \
	SAM_PINMUX(a, 16, c, periph)

/* pa16d_sercom3_pad0 */
#define PA16D_SERCOM3_PAD0 \
	SAM_PINMUX(a, 16, d, periph)

/* pa16e_tcc2_wo0 */
#define PA16E_TCC2_WO0 \
	SAM_PINMUX(a, 16, e, periph)

/* pa16f_tcc0_wo6 */
#define PA16F_TCC0_WO6 \
	SAM_PINMUX(a, 16, f, periph)

/* pa16h_gclk_io2 */
#define PA16H_GCLK_IO2 \
	SAM_PINMUX(a, 16, h, periph)

/* pa17_gpio */
#define PA17_GPIO \
	SAM_PINMUX(a, 17, gpio, gpio)

/* pa17a_eic_extint1 */
#define PA17A_EIC_EXTINT1 \
	SAM_PINMUX(a, 17, a, periph)

/* pa17b_ptc_x5 */
#define PA17B_PTC_X5 \
	SAM_PINMUX(a, 17, b, periph)

/* pa17c_sercom1_pad1 */
#define PA17C_SERCOM1_PAD1 \
	SAM_PINMUX(a, 17, c, periph)

/* pa17d_sercom3_pad1 */
#define PA17D_SERCOM3_PAD1 \
	SAM_PINMUX(a, 17, d, periph)

/* pa17e_tcc2_wo1 */
#define PA17E_TCC2_WO1 \
	SAM_PINMUX(a, 17, e, periph)

/* pa17f_tcc0_wo7 */
#define PA17F_TCC0_WO7 \
	SAM_PINMUX(a, 17, f, periph)

/* pa17h_gclk_io3 */
#define PA17H_GCLK_IO3 \
	SAM_PINMUX(a, 17, h, periph)

/* pa18_gpio */
#define PA18_GPIO \
	SAM_PINMUX(a, 18, gpio, gpio)

/* pa18a_eic_extint2 */
#define PA18A_EIC_EXTINT2 \
	SAM_PINMUX(a, 18, a, periph)

/* pa18b_ptc_x6 */
#define PA18B_PTC_X6 \
	SAM_PINMUX(a, 18, b, periph)

/* pa18c_sercom1_pad2 */
#define PA18C_SERCOM1_PAD2 \
	SAM_PINMUX(a, 18, c, periph)

/* pa18d_sercom3_pad2 */
#define PA18D_SERCOM3_PAD2 \
	SAM_PINMUX(a, 18, d, periph)

/* pa18e_tc3_wo0 */
#define PA18E_TC3_WO0 \
	SAM_PINMUX(a, 18, e, periph)

/* pa18f_tcc0_wo2 */
#define PA18F_TCC0_WO2 \
	SAM_PINMUX(a, 18, f, periph)

/* pa18h_ac_cmp0 */
#define PA18H_AC_CMP0 \
	SAM_PINMUX(a, 18, h, periph)

/* pa19_gpio */
#define PA19_GPIO \
	SAM_PINMUX(a, 19, gpio, gpio)

/* pa19a_eic_extint3 */
#define PA19A_EIC_EXTINT3 \
	SAM_PINMUX(a, 19, a, periph)

/* pa19b_ptc_x7 */
#define PA19B_PTC_X7 \
	SAM_PINMUX(a, 19, b, periph)

/* pa19c_sercom1_pad3 */
#define PA19C_SERCOM1_PAD3 \
	SAM_PINMUX(a, 19, c, periph)

/* pa19d_sercom3_pad3 */
#define PA19D_SERCOM3_PAD3 \
	SAM_PINMUX(a, 19, d, periph)

/* pa19e_tc3_wo1 */
#define PA19E_TC3_WO1 \
	SAM_PINMUX(a, 19, e, periph)

/* pa19f_tcc0_wo3 */
#define PA19F_TCC0_WO3 \
	SAM_PINMUX(a, 19, f, periph)

/* pa19h_ac_cmp1 */
#define PA19H_AC_CMP1 \
	SAM_PINMUX(a, 19, h, periph)

/* pa20_gpio */
#define PA20_GPIO \
	SAM_PINMUX(a, 20, gpio, gpio)

/* pa24_gpio */
#define PA24_GPIO \
	SAM_PINMUX(a, 24, gpio, gpio)

/* pa24a_eic_extint12 */
#define PA24A_EIC_EXTINT12 \
	SAM_PINMUX(a, 24, a, periph)

/* pa24c_sercom3_pad2 */
#define PA24C_SERCOM3_PAD2 \
	SAM_PINMUX(a, 24, c, periph)

/* pa24d_sercom5_pad2 */
#define PA24D_SERCOM5_PAD2 \
	SAM_PINMUX(a, 24, d, periph)

/* pa24e_tc5_wo0 */
#define PA24E_TC5_WO0 \
	SAM_PINMUX(a, 24, e, periph)

/* pa24f_tcc1_wo2 */
#define PA24F_TCC1_WO2 \
	SAM_PINMUX(a, 24, f, periph)

/* pa24g_usb_dm */
#define PA24G_USB_DM \
	SAM_PINMUX(a, 24, g, periph)

/* pa25_gpio */
#define PA25_GPIO \
	SAM_PINMUX(a, 25, gpio, gpio)

/* pa25a_eic_extint13 */
#define PA25A_EIC_EXTINT13 \
	SAM_PINMUX(a, 25, a, periph)

/* pa25b_ptc_x11 */
#define PA25B_PTC_X11 \
	SAM_PINMUX(a, 25, b, periph)

/* pa25c_sercom3_pad3 */
#define PA25C_SERCOM3_PAD3 \
	SAM_PINMUX(a, 25, c, periph)

/* pa25d_sercom5_pad3 */
#define PA25D_SERCOM5_PAD3 \
	SAM_PINMUX(a, 25, d, periph)

/* pa25e_tc5_wo1 */
#define PA25E_TC5_WO1 \
	SAM_PINMUX(a, 25, e, periph)

/* pa25f_tcc1_wo3 */
#define PA25F_TCC1_WO3 \
	SAM_PINMUX(a, 25, f, periph)

/* pa25g_usb_dp */
#define PA25G_USB_DP \
	SAM_PINMUX(a, 25, g, periph)

/* pa27_gpio */
#define PA27_GPIO \
	SAM_PINMUX(a, 27, gpio, gpio)

/* pa27a_eic_extint15 */
#define PA27A_EIC_EXTINT15 \
	SAM_PINMUX(a, 27, a, periph)

/* pa27f_sercom3_pad0 */
#define PA27F_SERCOM3_PAD0 \
	SAM_PINMUX(a, 27, f, periph)

/* pa27h_gclk_io0 */
#define PA27H_GCLK_IO0 \
	SAM_PINMUX(a, 27, h, periph)

/* pa28_gpio */
#define PA28_GPIO \
	SAM_PINMUX(a, 28, gpio, gpio)

/* pa28a_eic_extint8 */
#define PA28A_EIC_EXTINT8 \
	SAM_PINMUX(a, 28, a, periph)

/* pa28f_sercom3_pad1 */
#define PA28F_SERCOM3_PAD1 \
	SAM_PINMUX(a, 28, f, periph)

/* pa28h_gclk_io0 */
#define PA28H_GCLK_IO0 \
	SAM_PINMUX(a, 28, h, periph)

/* pa30_gpio */
#define PA30_GPIO \
	SAM_PINMUX(a, 30, gpio, gpio)

/* pa30a_eic_extint10 */
#define PA30A_EIC_EXTINT10 \
	SAM_PINMUX(a, 30, a, periph)

/* pa30d_sercom1_pad2 */
#define PA30D_SERCOM1_PAD2 \
	SAM_PINMUX(a, 30, d, periph)

/* pa30e_tcc1_wo0 */
#define PA30E_TCC1_WO0 \
	SAM_PINMUX(a, 30, e, periph)

/* pa30g_swd_clk */
#define PA30G_SWD_CLK \
	SAM_PINMUX(a, 30, g, periph)

/* pa30h_gclk_io0 */
#define PA30H_GCLK_IO0 \
	SAM_PINMUX(a, 30, h, periph)

/* pa31_gpio */
#define PA31_GPIO \
	SAM_PINMUX(a, 31, gpio, gpio)

/* pa31a_eic_extint11 */
#define PA31A_EIC_EXTINT11 \
	SAM_PINMUX(a, 31, a, periph)

/* pa31d_sercom1_pad3 */
#define PA31D_SERCOM1_PAD3 \
	SAM_PINMUX(a, 31, d, periph)

/* pa31e_tcc1_wo1 */
#define PA31E_TCC1_WO1 \
	SAM_PINMUX(a, 31, e, periph)

/* pa31g_swd_io */
#define PA31G_SWD_IO \
	SAM_PINMUX(a, 31, g, periph)

/* pb0_gpio */
#define PB0_GPIO \
	SAM_PINMUX(b, 0, gpio, gpio)

/* pb0a_eic_extint0 */
#define PB0A_EIC_EXTINT0 \
	SAM_PINMUX(b, 0, a, periph)

/* pb15_gpio */
#define PB15_GPIO \
	SAM_PINMUX(b, 15, gpio, gpio)

/* pb16_gpio */
#define PB16_GPIO \
	SAM_PINMUX(b, 16, gpio, gpio)

/* pb16a_eic_extint0 */
#define PB16A_EIC_EXTINT0 \
	SAM_PINMUX(b, 16, a, periph)

/* pb17_gpio */
#define PB17_GPIO \
	SAM_PINMUX(b, 17, gpio, gpio)

/* pb17a_eic_extint1 */
#define PB17A_EIC_EXTINT1 \
	SAM_PINMUX(b, 17, a, periph)

/* pb30_gpio */
#define PB30_GPIO \
	SAM_PINMUX(b, 30, gpio, gpio)

/* pb30f_sercom4_pad2 */
#define PB30F_SERCOM4_PAD2 \
	SAM_PINMUX(b, 30, f, periph)

/* pb31_gpio */
#define PB31_GPIO \
	SAM_PINMUX(b, 31, gpio, gpio)

/* pb31f_sercom4_pad1 */
#define PB31F_SERCOM4_PAD1 \
	SAM_PINMUX(b, 31, f, periph)

/* pc16_gpio */
#define PC16_GPIO \
	SAM_PINMUX(c, 16, gpio, gpio)

/* pc16f_glkc_io1 */
#define PC16F_GLKC_IO1 \
	SAM_PINMUX(c, 16, f, periph)

/* pc18_gpio */
#define PC18_GPIO \
	SAM_PINMUX(c, 18, gpio, gpio)

/* pc18f_sercom4_pad3 */
#define PC18F_SERCOM4_PAD3 \
	SAM_PINMUX(c, 18, f, periph)

/* pc19_gpio */
#define PC19_GPIO \
	SAM_PINMUX(c, 19, gpio, gpio)

/* pc19f_sercom4_pad0 */
#define PC19F_SERCOM4_PAD0 \
	SAM_PINMUX(c, 19, f, periph)
