/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/*
 * WARNING: this variant has package exception.
 *
 *   Read datasheet topics related to I/O Multiplexing and Considerations or
 *   Peripheral Signal Multiplexing on I/O Lines for more information.
 */

/* pa0_gpio */
#define PA0_GPIO \
	ATMEL_SAM_XXX(a, 0, gpio, gpio)

/* pa0b_per1_sig0 */
#define PA0B_PER1_SIG0 \
	ATMEL_SAM_XXX(a, 0, b, periph)

/* pa0c_per2_sig0 */
#define PA0C_PER2_SIG0 \
	ATMEL_SAM_XXX(a, 0, c, periph)

/* pa1_gpio */
#define PA1_GPIO \
	ATMEL_SAM_XXX(a, 1, gpio, gpio)

/* pa3_gpio */
#define PA3_GPIO \
	ATMEL_SAM_XXX(a, 3, gpio, gpio)

/* pa3_lpm */
#define PA3_LPM \
	ATMEL_SAM_XXX(a, 3, lpm, lpm)

/* pa4_gpio */
#define PA4_GPIO \
	ATMEL_SAM_XXX(a, 4, gpio, gpio)

/* pa4x_supc_wkup1 */
#define PA4X_SUPC_WKUP1 \
	ATMEL_SAM_XXX(a, 4, wkup1, wakeup)

/* pb0_gpio */
#define PB0_GPIO \
	ATMEL_SAM_XXX(b, 0, gpio, gpio)

/* pb0e_per4_sig1 */
#define PB0E_PER4_SIG1 \
	ATMEL_SAM_XXX(b, 0, e, periph)

/* pc0_gpio */
#define PC0_GPIO \
	ATMEL_SAM_XXX(c, 0, gpio, gpio)

/* pc0h_per7_sig2 */
#define PC0H_PER7_SIG2 \
	ATMEL_SAM_XXX(c, 0, h, periph)
