/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/* pa0_gpio */
#define PA0_GPIO \
	ATMEL_SAM_XXX(a, 0, gpio, gpio)

/* pa0b_per1_sig0 */
#define PA0B_PER1_SIG0 \
	ATMEL_SAM_XXX(a, 0, b, periph)

/* pa0c_per2_sig0 */
#define PA0C_PER2_SIG0 \
	ATMEL_SAM_XXX(a, 0, c, periph)

/* pa1_gpio */
#define PA1_GPIO \
	ATMEL_SAM_XXX(a, 1, gpio, gpio)

/* pa2_gpio */
#define PA2_GPIO \
	ATMEL_SAM_XXX(a, 2, gpio, gpio)

/* pa2x_extra_per_sig_extra */
#define PA2X_EXTRA_PER_SIG_EXTRA \
	ATMEL_SAM_XXX(a, 2, x, extra)

/* pa2s_jtag_tck */
#define PA2S_JTAG_TCK \
	ATMEL_SAM_XXX(a, 2, s, system)

/* pa4_gpio */
#define PA4_GPIO \
	ATMEL_SAM_XXX(a, 4, gpio, gpio)

/* pa4x_supc_wkup1 */
#define PA4X_SUPC_WKUP1 \
	ATMEL_SAM_XXX(a, 4, wkup1, wakeup)

/* pb0_gpio */
#define PB0_GPIO \
	ATMEL_SAM_XXX(b, 0, gpio, gpio)

/* pb0e_per4_sig1 */
#define PB0E_PER4_SIG1 \
	ATMEL_SAM_XXX(b, 0, e, periph)

/* pb0f_per5_sig1 */
#define PB0F_PER5_SIG1 \
	ATMEL_SAM_XXX(b, 0, f, periph)

/* pe15_gpio */
#define PE15_GPIO \
	ATMEL_SAM_XXX(e, 15, gpio, gpio)

/* pe15d_per12_sig4 */
#define PE15D_PER12_SIG4 \
	ATMEL_SAM_XXX(e, 15, d, periph)

/* pe15f_per14_sig4 */
#define PE15F_PER14_SIG4 \
	ATMEL_SAM_XXX(e, 15, f, periph)
